### ISSUE TITLE
Does this support arm?

### ISSUE THREAD

**Issue by CaptainDario** [wang-bin/fvp#103]
I am currently considering switching to this package for one of my applications.
Before I do this, I would like to ask if this package supports Windows and Linux on arm?

**Comment by wang-bin** [comment]
I think so, all dependencies already support arm. But flutter does not support cross compile linux/windows arm target, and i have no arm environment to test.

**Comment by wang-bin** [comment]
Where can I download flutter for arm linux/windows? I have arm macbook and virtual machine, maybe I can test in vm.

**Comment by wang-bin** [comment]
Perfect, no need to change anything! btw, you have to use flutter master channel because 3.22 has a bug on linux

<img width="1440" alt="image" src="https://github.com/wang-bin/fvp/assets/785206/3dff21d7-309b-44c2-82cb-d0b09b15f6f9">

**Comment by wang-bin** [comment]
does flutter support windows arm64? I have parallel desktops to test

**Comment by CaptainDario** [comment]
Yes, flutter works on Windows arm. The setup is the same as on Linux.

**Comment by wang-bin** [comment]
On windows I have to install many tools and not convenience, you can try yourself

**Comment by CaptainDario** [comment]
Thank you, I am gonna try in the coming days and will report here.

**Comment by wang-bin** [comment]
any progress?

**Comment by CaptainDario** [comment]
@wang-bin thank you for the reminder, I was really busy and forgot to check.
I cloned the repo and ran the example on the master branch (commit v0.20.1) and it worked perfectly!
Thanks for such an awesome package!
Maybe you can add Linux and Windows on arm as supported to the README so everybody knows that this works!

**Comment by wang-bin** [comment]
good iead, thanls
