### ISSUE TITLE
How to play audio from assets?

### ISSUE THREAD

**Issue by CaptainDario** [wang-bin/fvp#106]
I am trying to play some audio files that are included in my assets folder. But I cannot seem to figure out how to do that.
I can play an audio file from the filesystem using this code

```dart
final mdk.Player player = mdk.Player();
player.setMedia(
  '${audioFilesDir.path}/${widget.entry!.audio}.mp3',
  mdk.MediaType.audio);
player.state = mdk.PlaybackState.playing;
```

But trying to play from assets using something like 

```dart
player.setMedia(
  'assets/audios/my_fancy_track.wav',
  mdk.MediaType.audio);
```

does not work.

Is this currently not supported?

**Comment by CaptainDario** [comment]
So there is no way to read from assets using something like

`assets://audios/my_audio.wav`

? I need to copy your function `_assetUri`?

**Comment by wang-bin** [comment]
yes, copy that function. 'assets:' is a standard protocol on android. for other platforms, flutter assets are are regular files

**Comment by wang-bin** [comment]
no problem. i even considered moving it to player.dart and make it public

**Comment by CaptainDario** [comment]
That would be awesome!

**Comment by wang-bin** [comment]
`player.setAsset('assets/audios/my_fancy_track.wav')` will play the audio. `player.setAsset('assets/audios/my_fancy_track.wav', type: mdk.MediaType.audio)` will load an external audio track while playing a video set by `player.media` or `player.setAsset(asset)`

**Comment by CaptainDario** [comment]
Thank you this work perfectly!

**Comment by wang-bin** [comment]
available in the latest release
