### ISSUE TITLE
Is it possible to change the audio track?

### ISSUE THREAD

**Issue by Ansh-Rathod** [wang-bin/fvp#109]
Hi! Thank you for the amazing plugin! I'm using it to build the [video editor](https://x.com/anshrathodfr/status/1811747237464277473) app. I'm wondering if it's possible for me to have a feature to change the audio track from the chosen mkv file using this plugin or not, i haven't found the docs on that yet but I see few references of the audio tracks.

**Comment by wang-bin** [comment]
If you are using fvp via `video_player`, then it's no, because video_player has no such api. You have to use fvp backend api. 

```dart
import 'package:fvp/mdk.dart' as mdk;

...

final player = mdk.Player();
player.media = "video_file";
player.audioTracks = [1]; // the 2nd track. if does not exist(has only 1 audio track but select the 2nd track), then audio is disabled
await ret = player.prepare();
// now video is loaded, available tracks are known, you can also change the track here or later with a valid track number
final audioTracksCount = player.mediaInfo.audio.length;
```

**Comment by Ansh-Rathod** [comment]
Hey, Thank you for the quick reply and guiding me! Yes `player.activeAudioTracks = [0]` did work!
