### ISSUE TITLE
编译后的版本在一些NVIDIA显卡的windows设备崩溃

### ISSUE THREAD

**Issue by MCDFsteve** [wang-bin/fvp#110]
一开始以为是我编解码器的问题，我移除了这些自定义项，仅保留import的状态，编译后的exe在发给我的一些朋友测试的时候依然崩溃。共同特征是都是NVIDIA的显卡，从10系到30系都有，但是我另一个朋友的40系显卡没有问题（它普通模式运行也会崩溃，但是管理员权限运行则正常工作）。
尝试获取他们的报错打印，但是目前他们电脑剩余空间不足以安装Visual Studio了，如果拿到了报错的输出，我会第一时间追加在这里。

**Comment by wang-bin** [comment]
你试下最新的0.21.0，修了一个vcrt兼容性问题导致多数非最新系统上的必崩，和n卡没关系。还是不行的话贴个日志

**Comment by Predidit** [comment]
我也收到了类似的问题报告。

不过我觉得这与 msvc 无关。如果与 [microsoft/STL changelog](https://github.com/microsoft/STL/wiki/Changelog#vs-2022-1710) 相关，其应该表现为在使用最新版本的windows构建工具链得到的构建产物是损坏的。其构建产物将无法在任何地方运行。而不是现在这样只在部分使用NVIDIA显卡的设备上崩溃。

我在使用 NVIDIA 4070，遗憾的是我无法复现这一错误，如果我拿到了日志，会追加在这里。

**Comment by wang-bin** [comment]
我也有30系列n卡，没复现，也没有用户报类似问题，不过我这边是默认使用集显的，不知你们的是什么情况。vc错误一个月前我在mdk里修了，忘记在fvp修了，最近一个月的崩溃应该都是这个

**Comment by wang-bin** [comment]
我试了下集显和n卡运行都正常。

> 其构建产物将无法在任何地方运行

win11 版本新一点就能运行，我系统里的msvcp140.dll版本是之前是14.38.33135能运行，老一点会挂

**Comment by MCDFsteve** [comment]
> 你试下最新的0.21.0，修了一个vcrt兼容性问题导致多数非最新系统上的必崩，和n卡没关系。还是不行的话贴个日志

有效果。我将fvp手动指定为版本0.21.0（默认的flutter pub get似乎只会保持0.20.1版本）以后，编译的新的程序在朋友的电脑上测试不会出现闪退现象了，功能也都正常工作了。
