### ISSUE TITLE
Increase android minSdkVersion up to 21.

### ISSUE THREAD

**Issue by DovgopolsSerj** [wang-bin/fvp#111]
The Flutter SDK has raised the minimum android SDK to 21.
minSdkVersion 16 is specified in your package.
When building, flutter puts the entire SDK 16 that your package requests into the apk for compatibility.
The result is an apk of 108 Mb.
If you manually change the minSdkVersion to 21, then the apk gets 54 Mb.
This is a serious difference.

**Comment by wang-bin** [comment]
16 is too low, I will increase to 19 or 21. I'm curious what files in apk are larger than version 21.

**Comment by wang-bin** [comment]
I increase sdk version to 21. The binary size difference should be small between different versions, except new ndk will strip binaries.
