### ISSUE TITLE
[iOS] Add support for PIP

### ISSUE THREAD

**Issue by JulienDev** [wang-bin/fvp#113]
Hello,

First, I’d like to express my gratitude for the excellent work on this library—it's truly impressive.

I have a specific query regarding the fvp player's capabilities. As you might be aware, many video players for Flutter do not support Picture-in-Picture (PIP) mode on iOS devices. Could you please confirm whether the fvp player supports this feature? Additionally, if it does, could you share any examples or documentation on how to implement this?

Best regards,

**Comment by wang-bin** [comment]
no, pip is platform dependent, for ios a system player is required. you can try  https://github.com/tenghuanjun/CustomPictureInPicture/tree/master/pip_flutter

**Comment by JulienDev** [comment]
Thank you, I'll look into it
