### ISSUE TITLE
请添加截图api

### ISSUE THREAD

**Issue by yhsj0919** [wang-bin/fvp#118]
https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#void-snapshotsnapshotrequest-request-snapshotcallback-cb-void-vo_opaque--nullptr

**Comment by wang-bin** [comment]
之前有考虑过，不过不知道flutter里用什么接口表示图像

**Comment by yhsj0919** [comment]
可以用Uint8List直接返回数组，自己在flutter端处理

**Comment by wang-bin** [comment]
试下master分支

**Comment by wang-bin** [comment]
supported in v0.23.0
