### ISSUE TITLE
Can't build example app for android on linux

### ISSUE THREAD

**Issue by amr-kasem** [wang-bin/fvp#119]
I tried building for android it didn't success.
[log.txt](https://github.com/user-attachments/files/16447165/log.txt)

I also tried building for linux but it doesn't work the app launch with black screen only

**Comment by wang-bin** [comment]
Run
```
cd /home/amr/my-apps/fvp/android/.cxx/RelWithDebInfo/1q2k6e31/arm64-v8a
/home/amr/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/amr/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -DFLUTTER_PLUGIN_IMPL -Dfvp_plugin_EXPORTS -isystem /home/amr/my-apps/fvp/android/mdk-sdk/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -fno-rtti -fno-exceptions -ffunction-sections -fdata-sections -std=gnu++20 -MD -MT CMakeFiles/fvp_plugin.dir/fvp_plugin.cpp.o -MF CMakeFiles/fvp_plugin.dir/fvp_plugin.cpp.o.d -o CMakeFiles/fvp_plugin.dir/fvp_plugin.cpp.o -c /home/amr/my-apps/fvp/android/fvp_plugin.cpp -v
```
And show me the result.

BTW, don't use flutter in snap when possible, the compiler may conflict with system one.

**Comment by wang-bin** [comment]
also show me `flutter doctor -v` and linux run log, log can be enabled following the steps in issue template

**Comment by amr-kasem** [comment]
worked correctly using flutter without snap
Thank you very much

**Comment by wang-bin** [comment]
If using flutter from snap, enviroment var [`CPLUS_INCLUDE_PATH` is set to libc++ dirs in snap](https://github.com/canonical/flutter-snap/blob/main/env.sh#L14), which breaks the compilation. So snap is never recommended
