### ISSUE TITLE
[Subtitles] Add Ability to Change Text Size

### ISSUE THREAD

**Issue by JulienDev** [wang-bin/fvp#123]
Hello,

I tried to figure out how to change the subtitle text size, but I didn't find any way to do it. I also checked in libmdk, but it seems not supported. Could you please let me know how this can be achieved?

Thanks

**Comment by wang-bin** [comment]
yes, not supported yet

**Comment by wang-bin** [comment]
[upgrade dependencies](https://github.com/wang-bin/fvp?tab=readme-ov-file#upgrade-dependencies-manually) to support this feature, subtitle style can be set in `registerWith` https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#subtitle-properties

**Comment by wang-bin** [comment]
Upgrade dependency when [this build](https://github.com/wang-bin/mdk-sdk/actions/runs/11688313540) is completed, then new style will be applied in the next frame

**Comment by JulienDev** [comment]
I confirm it's working 👑
