### ISSUE TITLE
[Windows][Linux] Can't launch the app in debug mode

### ISSUE THREAD

**Issue by JulienDev** [wang-bin/fvp#125]
**Describe the bug**
I added Fvp v0.22.0 on Windows and Linux and the app is not launching anymore in debug mode. On other platforms MacOS/Android/iOS the app is launching in debug mode.

In release mode this is working fine on all platforms.

Flutter version: 3.22.3

**Log**
Windows
```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
FVP_DEPS_LATEST=
√ Built build\windows\x64\runner\Debug\player.exe
Problem getting monitor brightness
Debug service listening on ws://127.0.0.1:50118/s2r1Bx8b5VQ=/ws
Syncing files to device Windows...
```
Linux
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
FVP_DEPS_LATEST=
✓ Built build/linux/x64/debug/bundle/expert
0.29.0 (git 0a3bd27) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at [[gmail.com](http://gmail.com/)](http://gmail.com/)>
Build for: Linux 4KB x86_64; glibc2.24/2.39 libc++190000; Clang19.0.0 (++20240721042146+d69eb7b7ffb3-1~exp1~20240721042318.1816); 12:06:18 Jul 21 2024
Debug service listening on ws://127.0.0.1:40435/Y8fDJmQnUEQ=/ws
Syncing files to device Linux...

- * (expert:26950): WARNING **: 11:05:37.482: Unable to retrieve framework response: Message is not valid JSON
- * (expert:26950): WARNING **: 11:05:37.482: Unable to retrieve framework response: Message is not valid JSON
- * (expert:26950): WARNING **: 11:05:44.833: Unable to retrieve framework response: Message is not valid JSON
- * (expert:26950): WARNING **: 11:05:44.976: Unable to retrieve framework response: Message is not valid JSON
- * (expert:26950): WARNING **: 11:05:46.224: Unable to retrieve framework response: Message is not valid JSON
- * (expert:26950): WARNING **: 11:05:46.688: Unable to retrieve framework response: Message is not valid JSON
- * (expert:26950): WARNING **: 11:05:59.130: Unable to retrieve framework response: Message is not valid JSON
```

**Comment by wang-bin** [comment]
can you debug in gdb?

**Comment by JulienDev** [comment]
Sorry but I don't know how I can debug it 😔

**Comment by wang-bin** [comment]
`gdb path_of_executable`, then you will be in gdb interactive mode, type `r` and return, then your app will run. If app crashes, show me gdb output

**Comment by JulienDev** [comment]
Thanks!
The problem seems only to happen with Android Studio because when I launch the app by running `build/linux/x64/debug/bundle/myapp` everything is working perfectly.
If I launch it using "flutter run" it works too.

**Comment by wang-bin** [comment]
> On other platforms MacOS/Android/iOS the app is launching in debug mode.

> The problem seems only to happen with Android Studio because when I launch the app by running build/linux/x64/debug/bundle/myapp everything is working perfectly.

I don't understand, which target fails?

**Comment by JulienDev** [comment]
When I run the app in debug mode from Android Studio by pressing the "run button":
- MacOS/Android/iOS: ✅
- Windows/Linux: ❌

When I run the app in debug mode using "flutter run":
- MacOS/Android/iOS/Windows/Linux: ✅

I don't know exactly why it's happening, maybe it's related to hotreload or something like that 🤷🏻‍♂️

**Comment by wang-bin** [comment]
android studio only supports android. why do you run win/linux in android studio? it's impossible.

**Comment by JulienDev** [comment]
No no, Android Studio supports all flutter targets: web, android, ios, windows, linux
For example, this is a screenshot on my Mac, as you can see we can select the target we want to launch. Then hot reload will work fine on every target.
<img width="584" alt="image" src="https://github.com/user-attachments/assets/cbd8ba5f-ea3e-4d9a-b023-7da75c33614a">

**Comment by wang-bin** [comment]
Please enable log following issue template, and paste the log

**Comment by wang-bin** [comment]
I can run linux in android studio without error

**Comment by JulienDev** [comment]
Ok, I think it's due to my project configuration because the sample is running fine. Will post a solution later if I find the reason. Thanks for your time 🙏🏻

**Comment by Bonfra04** [comment]
Hi, just to add some more context:
I'm experiencing the same issue with the integrated vscode debugger. Running from the CLI `flutter run ...` works just fine. It seems like the debugger is not able to attach until some hot reloads. The logs are virtually the same so it might be something related to the IDEs.

**Comment by wang-bin** [comment]
> Hi, just to add some more context: I'm experiencing the same issue with the integrated vscode debugger. Running from the CLI `flutter run ...` works just fine. It seems like the debugger is not able to attach until some hot reloads. The logs are virtually the same so it might be something related to the IDEs.

IDE or debugger bug

**Comment by wang-bin** [comment]
what about removing `dartPluginClass:` lines in fvp's pubspec.yaml?

**Comment by Bonfra04** [comment]
Testing on Windows it seems that removing the `dartPluginClass:` (for Windows specifically) fixes the issue. Not sure about linux but I guess will work as well.

Just an observation, not sure if it's relevant:
The vscode debugger uses different colors for different sources of outputs. compilation stuff like running gradle for android and things like that is printed in yellow while the rest of the runtime is printed in blue. If some output is produced by the code triggered by the `dartPluginClass` in the pubspec file, the debug console colors it in yellow; not in blue. Maybe that code execution is treated differently and does some weird stuffs? idk

**Comment by wang-bin** [comment]
please try master branch

**Comment by Bonfra04** [comment]
Yup works perfectly :)
 Still, I'm just testing on Windows so I cannot confirm for Linux but I think the principle is the same
