### ISSUE TITLE
[CC] Can't control closed captions track

### ISSUE THREAD

**Issue by JulienDev** [wang-bin/fvp#126]
**Describe the bug**
Hello, I've noticed that we cannot control the closed captions track, and they are enabled by default. I want to clarify that I'm referring specifically to closed captions, not subtitles. I can share a link privately for you to test it yourself.

**Expected behavior**
Ideally, we should be able to choose which track to use, or, if that’s too complex, it would be helpful to disable closed captions by default.

**Comment by wang-bin** [comment]
You can share your link via email.

Choosing cc track is not supported. To disable cc, If you are using video_player
```dart
registerWith(options: {
  'player': {
      'cc': '0'
  }
});
```

if you are using backend api, `player.setProperty('cc', '0');`

**Comment by JulienDev** [comment]
Tested, working! Thank you!
