### ISSUE TITLE
is there any way i can have functionality to jump to next/previous frame?

### ISSUE THREAD

**Issue by Ansh-Rathod** [wang-bin/fvp#127]
HII, I think I saw this feature in vlc or some other editor where you can jump to the next/previous frame change with buttons I'm thinking of getting that frame change data using ffmpeg but I wonder if it's possible in the player it self or not?

**Comment by wang-bin** [comment]
next: `player.seek(position: 1, flags: mdk.SeekFlag(mdk.SeekFlag.fromNow | mdk.SeekFlag.frame));`, previous: `player.seek(position: -1, flags: mdk.SeekFlag(mdk.SeekFlag.fromNow | mdk.SeekFlag.frame));`

**Comment by Ansh-Rathod** [comment]
WOW, so it does have this functionality! Yes, I'm using backend API only, huge thank you for the response & plugin it self!
