### ISSUE TITLE
Slow loading on lastest version 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [wang-bin/fvp#129]
**Describe the bug**
loading local files are a bit slower, it loads for a while before starting the playback (on android)

on macos its the same speed as previous versions 

network has the same problem, but it may be due internet speed
**Expected behavior**
it was much faster on previous versions 

**Log**

https://justpaste.it/aifn6

**Comment by wang-bin** [comment]
The difference is previously ffmpeg 6.1 was used, [now it's ffmpeg master branch](https://github.com/wang-bin/mdk-sdk/commit/b3c7f165fbbacfe002f2640a4099fa79135a53fb). We noticed the performance downgrade a few months ago in ffmpeg 7.0 and later. We guess ffmpeg code is miscompiled or is broken. Can you try this https://sourceforge.net/projects/avbuild/files/android/ffmpeg-master-android-revert-8c936e9.tar.gz/download

**Comment by abdelaziz-mahdy** [comment]
> The difference is previously ffmpeg 6.1 was used, [now it's ffmpeg master branch](https://github.com/wang-bin/mdk-sdk/commit/b3c7f165fbbacfe002f2640a4099fa79135a53fb). We noticed the performance downgrade a few months ago in ffmpeg 7.0 and later. We guess ffmpeg code is miscompiled or is broken. Can you try this https://sourceforge.net/projects/avbuild/files/android/ffmpeg-master-android-revert-8c936e9.tar.gz/download

Will try and let you know, can we open an issue for ffmpeg maybe it's something they can fix?

**Comment by wang-bin** [comment]
Need more tests to confirm which ffmpeg commit breaks

**Comment by abdelaziz-mahdy** [comment]
> Need more tests to confirm which ffmpeg commit breaks

Okay, I will try to use the binaries you provided and if all is good then we can revert to it until we are sure all good I guess.

**Comment by abdelaziz-mahdy** [comment]
i am sorry i am confused on how to use this

> The difference is previously ffmpeg 6.1 was used, [now it's ffmpeg master branch](https://github.com/wang-bin/mdk-sdk/commit/b3c7f165fbbacfe002f2640a4099fa79135a53fb). We noticed the performance downgrade a few months ago in ffmpeg 7.0 and later. We guess ffmpeg code is miscompiled or is broken. Can you try this https://sourceforge.net/projects/avbuild/files/android/ffmpeg-master-android-revert-8c936e9.tar.gz/download

**Comment by wang-bin** [comment]
replace `mdk-sdk/lib/arm64-v8a/libffmpeg.so` and rebuild

**Comment by abdelaziz-mahdy** [comment]
> replace `mdk-sdk/lib/arm64-v8a/libffmpeg.so` and rebuild

doing that made the loading go from 3 sec to less than 0.5 sec, very weird that the higher version of ffmpeg has that problem

**Comment by wang-bin** [comment]
I'm [reverting that commit](https://github.com/wang-bin/avbuild/commit/5f058e50cca3f08ee1ea912b601a0e354ce19234) in my build. I don't why, only android is slow, maybe a compiler bug

**Comment by abdelaziz-mahdy** [comment]
if you need me to test anything let me know , i dont mind trying again

**Comment by wang-bin** [comment]
the latest mdk's ffmpeg is patched. you can rebuild with env var `FVP_DEPS_LATEST=1`

**Comment by abdelaziz-mahdy** [comment]
ok thank you very much <3
