### ISSUE TITLE
 macos seek gets stuck or seek is delayed

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [wang-bin/fvp#130]
**Describe the bug**
sometimes multiple seeks gets stuck i think, like if requested alot of seeks it waits for sometime then seeks and sometime audio is out of sync and video is stuck 

maybe related to this one https://github.com/wang-bin/fvp/issues/117

i was able to produce it on macos, dont know if happens on other platforms or not 
**Expected behavior**
seeks without a problem and maybe ignore same seek ?

**Log**
https://justpaste.it/ehi4k

**Comment by wang-bin** [comment]
if seeking can completed after a few seconds, it's not a bug, maybe download speed is low

**Comment by abdelaziz-mahdy** [comment]
will recheck and let you know if its really a problem
