### ISSUE TITLE
Drop frames problem fps is very bad

### ISSUE THREAD

**Issue by isnzenauz** [wang-bin/fvp#132]
hi dear,
i have problem with fvp drop frames on android (mobile, tv) im trying to use **AMediaCodec and FFmpeg** but his give me same results frame drops i test it in: XIAOMI MI BOX S2 (Android), And mobile RED MAGIC 6, Poco x3 Pro, Tecno Spark 8 tecno spark 10 pro, give me same results, drop frames in LIVE M3u8, and Movies MP4, MKV

thank you to help me.

**Comment by wang-bin** [comment]
show me the log following issue template

**Comment by isnzenauz** [comment]
Hy sir
That what i see in debuge

I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000
I/AudioTrack(21381): AudioTrack::setVolume L:1.000000 R:1.000000 and the pakage is com.poppycorn.rax.poppycorn

and if the log file if exist where i can find it

**Comment by isnzenauz** [comment]
Im using thé logger his give me same results

**Comment by isnzenauz** [comment]
His note give me why thé live stream and long vidéos go to drop frames

**Comment by isnzenauz** [comment]
His give me same results, idont see anything about drop frames
