### ISSUE TITLE
[Enhancement] Expose listening APIs

### ISSUE THREAD

**Issue by bdlukaa** [wang-bin/fvp#139]
Currently, the fvp native player's APIs lack events or methods for directly listening to changes in position, duration, and buffering state. This makes it difficult to create features like progress bars, time displays, or custom buffering indicators. Exposing these APIs would significantly improve the developer experience and enable the creation of more advanced playback functionalities. The current native player APIs do not provide any built-in mechanisms for developers to track or react to changes in position, duration, or buffering.

## Proposal

We propose the following adding some API improvements, like:

`player.onPositionChange((duration) {})`

and similar methods for other options.

**Comment by wang-bin** [comment]
events are already in video_player and video_player_mdk.dart, the can be reused in your code
