### ISSUE TITLE
IOS 0.24.1直接崩溃，100%，随便一个视频都不可以

### ISSUE THREAD

**Issue by yemin82** [wang-bin/fvp#140]
![image](https://github.com/user-attachments/assets/6528db1a-4b4a-49c1-a574-5607e7bef47e)

**Comment by yemin82** [comment]
flutter: mdk.FINE: 10:42:03.134: creating video decoder: videotoolbox...
flutter: mdk.FINE: 10:42:03.135: starting decode loop thread mdk.adec1@0x70000e5c7000
flutter: fvp.FINE: 10:42:03.135: 999382246 player5065694928 onEvent: thread.audio -  - 1
flutter: mdk.FINE: 10:42:03.136: opening video decoder: videotoolbox...
flutter: mdk.FINE: 10:42:04.889: audio stream#1 starting decoding loop from decoder index 0...
flutter: mdk.FINE: 10:42:04.890: creating audio decoder: auto...
flutter: mdk.FINE: 10:42:04.890: opening ffmpeg video decoder: h264
               AQMEIO.cpp:198   timed out after 2.500s (2135 2136); suspension count=0 (IOSuspensions: )
106267          HALC_ProxyIOContext.cpp:1346  HALC_ProxyIOContext::IOWorkLoop: skipping cycle due to overload
flutter: mdk.INFO: 10:42:04.891: opening audio decoder: FFmpeg...
flutter: mdk.FINE: 10:42:04.891: opening ffmpeg audio decoder: aac
flutter: mdk.FINE: 10:42:04.891: AVCodec.Audio[aac.] decoder: 1 Single threads
 MEDeviceStreamClient.cpp:467   AQME Default-InputOutput: client stopping after failed start: <AudioQueueObject@0x1291ae600; [5380]; play>; running count now 1
flutter: mdk.FINE: 10:42:04.891: aac f32p, stereo @44100Hz
flutter: fvp.FINE: 10:42:04.892: 999382246 player5065694928 onEvent: decoder.audio - FFmpeg - 0
flutter: mdk.INFO: 10:42:04.892: ***buffering progress 100%***
flutter: mdk.FINE: 10:42:04.892: default 0x12df06760 FrameReader::update MediaStatus 0X14=>0X124
flutter: mdk.FINE: 10:42:04.892: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 10:42:04.892:
flutter: fvp.FINE: 10:42:04.893: 999382246 player5065694928 onMediaStatus: MediaStatus(+loaded+buffering) => MediaStatus(+loaded+prepared+buffered)
flutter: mdk.INFO: 10:42:04.893: ++++++++++++BUFFERING END++++++++++++
flutter: mdk.FINE: 10:42:04.893:
flutter: fvp.FINE: 10:42:04.893: 999382246 player5065694928 onEvent: reader.buffering -  - 100
flutter: mdk.FINE: 10:42:04.893: audio stream#1 sending 1 invalid AOT frame @1.440000s. seeking: 0
flutter: mdk.FINE: 10:42:04.893: 0x12e80d600 1st audio frame @1.440000
flutter: mdk.INFO: 10:42:04.894: 0x12e80d600 seek end audio frame @1.440000 seek_pos_: -1, sync_ao_ 1
flutter: mdk.FINE: 10:42:04.894: Selected avfilter runtime version: 10.2.102 (build: 10.2.102), license: LGPL version 2.1 or later
flutter: mdk.FINE: 10:42:04.894: AudioRenderer format: f32, stereo @44100Hz, requested: f32p, stereo @44100Hz
flutter: mdk.FINE: 10:42:04.896: AudioRenderer format changed and reinitialize
flutter: mdk.FINE: 10:42:04.897: 0x10eb121c0mdk::NativeVideoBufferPool::NativeVideoBufferPool()
flutter: mdk.FINE: 10:42:04.897: Try to use IOSurface OpenGL(ES) interop: false
flutter: mdk.FINE: 10:42:04.897: AVCodec.Video[h264.] decoder: 1 Single threads
flutter: mdk.FINE: 10:42:04.897: unsupported avcodec options:  hwcontext=videotoolbox shader_resource=0
flutter: mdk.FINE: 10:42:04.897: [FFmpeg:https] Opening 'https://play.modujx15.com/20240816/sKDubzQ3/1006kb/hls/RH6oAdSN.ts' for readingh264 1920x960  yuv420p
flutter: mdk.FINE: 10:42:13.392:

**Comment by yemin82** [comment]
之前一直用0.19.0，虽然有点小毛病，但是还是可以用，最近发现0.19.0有一个视频播放不了，但是ios自带播放器可以播放，就想升级fvp看看，结果崩溃了。。
0.19.0，不能播放的视频：https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8

**Comment by yemin82** [comment]
这个视频我估计在0.24.1也是不行的，应为0.24.1打开这个视频都不会崩溃了，也不会报错
flutter: mdk.FINE: 10:47:44.542: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 10:47:44.542:
flutter: fvp.FINE: 10:47:44.543: 928238212 player4492213264 onMediaStatus: MediaStatus(+loaded) => MediaStatus(+loaded+buffering)
flutter: mdk.INFO: 10:47:44.543: ++++++++++++BUFFERING START++++++++++++
flutter: mdk.FINE: 10:47:44.543:
flutter: fvp.FINE: 10:47:44.544: 928238212 player4492213264 onEvent: reader.buffering -  - 0
flutter: mdk.FINE: 10:47:44.545: default 0x10bc1c630 FrameReader::update MediaStatus 0X14=>0X54
flutter: fvp.FINE: 10:47:44.545: 928238212 player4492213264 onMediaStatus: MediaStatus(+loaded+buffering) => MediaStatus(+loaded+buffering+end)
flutter: mdk.FINE: 10:47:44.545: read packet error. FrameReader@0x10bc1c630 sending Packet::End to all packet queues. PacketIO@0x10b72e630 ->url: https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8
flutter: mdk.FINE: 10:47:44.545: default FrameReader0x10bc1c630 state: 0=>2=>1, 1
flutter: mdk.FINE: 10:47:44.546: default FrameReader0x10bc1c630 update state: 0=>1
flutter: fvp.FINE: 10:47:44.546: 928238212 player4492213264 onPlaybackStateChanged: PlaybackState.stopped => PlaybackState.playing
flutter: mdk.FINE: 10:47:44.547: default FrameReader0x10bc1c630 state: 1=>1=>2, 1
flutter: mdk.FINE: 10:47:44.547: default FrameReader0x10bc1c630 update state: 1=>2
flutter: fvp.FINE: 10:47:44.547: 928238212 player4492213264 onPlaybackStateChanged: PlaybackState.playing => PlaybackState.paused
flutter: mdk.FINE: 10:47:44.547: before changed() 54
flutter: mdk.FINE: 10:47:44.547: default FrameReader0x10bc1c630 state: 2=>2=>0, 0
flutter: mdk.FINE: 10:47:44.548: 0x10bc1c630 unload, current status 0x54, invalid: 0, loading: 0, loaded: 4, buffering: 16, seeking: 0, prepared: 0, EOF: 64
flutter: mdk.FINE: 10:47:44.548: 0x600003d01b80 request avformat input interrupt
flutter: mdk.INFO: 10:47:44.548: ***buffering progress 100%***
flutter: mdk.FINE: 10:47:44.548: default 0x10bc1c630 FrameReader::update MediaStatus 0X54=>0X164
flutter: mdk.FINE: 10:47:44.548: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 10:47:44.549:
flutter: fvp.FINE: 10:47:44.549: 928238212 player4492213264 onMediaStatus: MediaStatus(+loaded+buffering+end) => MediaStatus(+loaded+prepared+buffered+end)
flutter: mdk.INFO: 10:47:44.549: ++++++++++++BUFFERING END++++++++++++
flutter: mdk.FINE: 10:47:44.549:
flutter: fvp.FINE: 10:47:44.549: 928238212 player4492213264 onEvent: reader.buffering -  - 100
3
flutter: mdk.FINE: 10:47:44.550: interrupted by user
flutter: mdk.FINE: 10:47:44.550: 0x700009cdd000default 0x10bc1c630 update @1149: reset status_mask. status: 161
flutter: mdk.FINE: 10:47:44.550: default 0x10bc1c630 FrameReader::update MediaStatus 0X164=>0X41
flutter: fvp.FINE: 10:47:44.551: 928238212 player4492213264 onMediaStatus: MediaStatus(+loaded+prepared+buffered+end) => MediaStatus(+unloaded+end)
flutter: mdk.FINE: 10:47:44.551: default FrameReader0x10bc1c630 state: 2=>0=>0, 1
flutter: mdk.FINE: 10:47:44.551: default FrameReader0x10bc1c630 update state: 2=>0
flutter: fvp.FINE: 10:47:44.551: 928238212 player4492213264 onPlaybackStateChanged: PlaybackState.paused => PlaybackState.stopped

**Comment by yemin82** [comment]
1

**Comment by wang-bin** [comment]
你把截图里红色那条错误提示显示完整看看

**Comment by yemin82** [comment]
这个已经关闭了，估计是flutter和ios的mdk版本好匹配问题，我手动下载的现在都改mdk0.29.0可以了

**Comment by wang-bin** [comment]
master 分支已修复
