### ISSUE TITLE
Subtitles m3u8 mkv mp4

### ISSUE THREAD

**Issue by isnzenauz** [wang-bin/fvp#142]
Hello sir
How i Can show the track subtitles have in MP4 and mkc from m3u8

**Comment by wang-bin** [comment]
Do you have a url to test?

**Comment by isnzenauz** [comment]
yes i can create iptv subscription for you, but i can put it here in public where i can sent you the M3u8 of iptv ?

**Comment by wang-bin** [comment]
via my email

**Comment by isnzenauz** [comment]
Hello Sir i send it to your email - subject of email is (Subscription TV M3u8 for WangBin)
wbsecg1@gmail.com

**Comment by wang-bin** [comment]
Your m3u8 is invalid, you can't put mkv, avi into m3u8
