### ISSUE TITLE
windows arm (colors inverted)

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [wang-bin/fvp#152]
**Describe the bug**
colors are inverted when playing video on windows arm 
and it plays correctly on macos version

fvp version: 0.26.1
**Expected behavior**
colors to be correct 

**Log**
Add
https://justpaste.it/c3aw3

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/2e8ac74e-b39c-4eb2-8974-b1b43a8e8f59">

**Comment by wang-bin** [comment]
Can you build [this example](https://github.com/wang-bin/mdk-examples/tree/master/flutter/simple) for me? I can test in parallels desktop.

**Comment by abdelaziz-mahdy** [comment]
i dont have a windows machine, i am building the app using github actions and testing it using vmware fusion (which runs a windows machine with arm arch)

**Comment by wang-bin** [comment]
How to build in github actions?

I don't have build environment, but https://github.com/wang-bin/fvp/issues/103 this user tested on arm and no such issue.

**Comment by wang-bin** [comment]
You can also test `./glfwplay.exe -logfile test.log -c:v MFT -d3d11 test.mp4`

**Comment by abdelaziz-mahdy** [comment]
> How to build in github actions?
> 
> I don't have build environment, but https://github.com/wang-bin/fvp/issues/103 this user tested on arm and no such issue.


You already build in. GitHub actions using this 
https://github.com/wang-bin/mdk-examples/blob/master/.github/workflows/main.yml


It may be a VMware issue so I will check again using a player or the command you provided 



What is glfwplay.exe?

**Comment by wang-bin** [comment]
Are you running x64 binaries on arm64? I can reproduce a similar issue. but arm64 binaries works fine for me.

glfwplay.exe is a test program in [mdk-sdk](https://sourceforge.net/projects/mdk-sdk/files/nightly/mdk-sdk-windows-desktop-vs2022.7z/download)

**Comment by abdelaziz-mahdy** [comment]
I don't know how to build an arm version using GitHub actions 😅

So yes it looks like I am building and running x86 version

**Comment by wang-bin** [comment]
should be fixed in the latest mdk

**Comment by abdelaziz-mahdy** [comment]
Will test it and let you know, thank you
