### ISSUE TITLE
Commercial use of this package?

### ISSUE THREAD

**Issue by Ansh-Rathod** [wang-bin/fvp#158]
Hi, Can I use this package in the commercial app? I have seen this package uses the ffmpeg libs underhood and I was reading the licensing on the FFmpeg website that if I want to use ffmpeg in commercially then I have to use it under LGPL and libraries should be dynamically linked. and if you use ffmepg under GPL you have to open-source the app. I clearly dont know but can you please help me get a clear view on this?

**Comment by wang-bin** [comment]
ffmpeg used in this package is lgpl, all changes can be found in my avbuild repo. the playback library libmdk used by fvp is also free for commercial usage.

**Comment by Ansh-Rathod** [comment]
Great! that means it's a green light. thank you for clearing this.

**Comment by Ansh-Rathod** [comment]
btw can I use the ffmpeg from this package?

**Comment by wang-bin** [comment]
for distributing, the ffmpeg binary in fvp is enough. but it's not enough for compiling, you need headers and libs for compiling and linking, which can be download from https://sourceforge.net/projects/avbuild/files/  (I use packages with ends with -lite or -lite-lto).  libmdk for iOS is linked against static ffmpeg, so you have to use another ffmpeg.framework, the framework can be generated with [dylib2framework.sh](https://github.com/wang-bin/avbuild/blob/master/tools/dylib2framework.sh) in [prebuilt package](https://sourceforge.net/projects/avbuild/files/iOS/ffmpeg-master-iOS-lite-lto-shared.tar.xz/download)

**Comment by Ansh-Rathod** [comment]
Thank you so much.

**Comment by wang-bin** [comment]
I also uploaded [FFmpeg.xcframework](https://sourceforge.net/projects/avbuild/files/xcframework/FFmpeg.xcframework-master-lite.tar.xz/download) for iOS(and all apple platforms). You can use xcframework and headers in `include` dir to build your app, and  FFmpeg.framework will be copied to your app bundle.

**Comment by Ansh-Rathod** [comment]
I finally figured it out, btw I was building this app and it uses fvp, now I have released the beta version https://fimosa.app you can just email me saying hi at help.fimosa@gmail.com and I'll send you the license key.

**Comment by wang-bin** [comment]
Thanks
