### ISSUE TITLE
Support HEVC with unknown profile bitstream

### ISSUE THREAD

**Issue by Predidit** [wang-bin/fvp#159]
假期快乐

很抱歉又来打扰大佬了，我遇到了一个 fvp 无法播放的 HEVC 视频流。但是可以被 mpv 正确播放。也可以被 AVPlayer 播放。

链接为 https://hx1kjo7k0d.senhewenhua.com:11451/cache/5Yir5b2T5qyn5bC86YWx5LqGICgxKS5tcDQ=.mp4?verify=1727694215-3gPcr7bH6DR02r%2BnqbO02jkb7Pqpz%2B%2BbzSa%2FIHtr7tA%3D  (如果失效的话提醒我补档)

ffprobe 结果如下

```
[hevc @ 000002A1D0257400] Unknown profile bitstream
    Last message repeated 1 times
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://hx1kjo7k0d.senhewenhua.com:11451/cache/5Yir5b2T5qyn5bC86YWx5LqGICgxKS5tcDQ=.mp4?verify=1727694215-3gPcr7bH6DR02r%2BnqbO02jkb7Pqpz%2B%2BbzSa%2FIHtr7tA%3D':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : ShanaEncoder
  Duration: 00:23:39.97, start: 0.000000, bitrate: 1505 kb/s
  Stream #0:0[0x1](und): Video: hevc (hev1 / 0x31766568), yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], 1306 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[hevc @ 000002A1D025B140] Unknown profile bitstream
```

这是编解码器支持的问题还是非标准格式视频流?

**Comment by Predidit** [comment]
我又尝试了一下最新的 mdk-sdk 中的 glfwplay 。也可以正确播放，使用最新 mdk-sdk 中的 ffmpeg.dll 替换本地 ffmpeg.dll 不能解决问题。

看上去这是一个 fvp 的问题

**Comment by wang-bin** [comment]
得看下日志。视频用浏览器打不开，提示`Sorry, you have been blocked`。

**Comment by Predidit** [comment]
链接过期了，这个链接的有效期似乎只有几个小时。

这是新的

https://zb02x2g92u.senhewenhua.com:11451/cache/5Yir5b2T5qyn5bC86YWx5LqGICgxKS5tcDQ=.mp4?verify=1727715823-jYJKnt7eh%2BlDGePzXguM3RwYW4cYb6FsFBfgTaYLFAw%3D

来源是 https://www.cyc-anime.net/

**Comment by wang-bin** [comment]
我用一个简单的flutter例子测了下能播，程序下载：https://github.com/wang-bin/mdk-examples/actions/runs/11109300127

**Comment by wang-bin** [comment]
不过新的链接用ffprobe没看到`Unknown profile bitstream`提示

**Comment by Predidit** [comment]
我现在也复现不了这个问题了。

非常抱歉打扰了您，如果我掌握了这个问题的规律，会在这里更新。
