### ISSUE TITLE
使用mdk.dart作为播放器后端的时候，ass字幕显示似乎有些问题。

### ISSUE THREAD

**Issue by MCDFsteve** [wang-bin/fvp#161]
播放一些内嵌ass双语字幕的mkv时，字幕会堆叠在一起（一些则能正常显示）。
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/241324e5-f113-4083-8c32-a59a75386aac">
似乎是ass的一些样式未正确生效。是我没配置一些内容导致的吗
上传了两份ass（改成了txt后缀）。KimiNoNaWa的字幕，显示会堆叠。SteinsGate的字幕，各种样式都正常显示（在之前使用video_player配合fvp的时候，KimiNoNaWa的字幕也是正常工作的）
[[Haruhana] Kimi no Na wa. [BDRip][HEVC-10bit 1080p].txt](https://github.com/user-attachments/files/17265529/Haruhana.Kimi.no.Na.wa.BDRip.HEVC-10bit.1080p.txt)
[[KissSub][Steins;Gate][01][GB_BIG5_JP][BDrip][1080P][HEVC] 起源与终结的序章.txt](https://github.com/user-attachments/files/17265530/KissSub.Steins.Gate.01.GB_BIG5_JP.BDrip.1080P.HEVC.txt)

**Comment by wang-bin** [comment]
等 https://github.com/wang-bin/mdk-sdk/actions/runs/11192124796 编译完后你更新下依赖。

另外，master分支对VideoPlayerController做了扩展，增加了一些方法，比如`setExternalSubtitle()`，这样可以复用video_player现有逻辑，不必直接使用mdk.dart写一堆代码。这些方法都要在controller.initialize()完成之后才有效果

**Comment by MCDFsteve** [comment]
感谢，问题解决了
