### ISSUE TITLE
Support HTTP header

### ISSUE THREAD

**Issue by Predidit** [wang-bin/fvp#163]
fvp 在 android/macOS/iOS 上支持 http 标头 

但是 fvp 在 windows/linux 平台设置的 http 标头会被忽略

这是一个预期行为吗，我们可以为这些平台添加 http header 支持吗，这可以让我们播放通过 http header 进行权限校验的视频

eg: 
https://vod.2bdm.cc/2024/07/ytlwzadsg/01.mp4?verify=1728439304-BmxbrSloMKliIVjNsy38l5wnsPJ8Jv6a%2BYHK55gneVc%3D

需要referer设定为 https://www.clicli.pro/

**Comment by Predidit** [comment]
我注意到 fvp 通过设置 avio 来支持 http header，这似乎不应该有问题，ffmpeg原生有 http header 支持

所以这是一个 bug ?

**Comment by wang-bin** [comment]
android/ios/mac是也是同样用法？
