### ISSUE TITLE
请修正mdk-sdk的下载地址

### ISSUE THREAD

**Issue by AnonymHK** [wang-bin/fvp#17]
Downloading mdk-sdk from https://sourceforge.net/projects/mdk-sdk/files/nightly/mdk-sdk-android.7z

https://sourceforge.net/projects/mdk-sdk/files/nightly/mdk-sdk-android.7z
这个Url不是一个有效的下载地址，仅是一个下载页面！
https://altushost-swe.dl.sourceforge.net/project/mdk-sdk/nightly/mdk-sdk-android.7z
这个或许是一个正确的选择！

**Comment by wang-bin** [comment]
will redirect to a mirror link, for example the url you provided

**Comment by wang-bin** [comment]
you can show me the full build log

**Comment by wang-bin** [comment]
the url will be redirected to a real url. what's your cmake version? Here is a CMakeLists.txt you can test
```
cmake_minimum_required(VERSION 3.16)
project(test)
file(DOWNLOAD https://sourceforge.net/projects/mdk-sdk/files/nightly/mdk-sdk-android.7z ${CMAKE_CURRENT_SOURCE_DIR}/a.7z SHOW_PROGRESS LOG dl STATUS st)
message("status: ${st}, log: ${dl}")
```

run `cmake .`  and show me the output. on linux, wsl or mac, run `cmake . 2>&1 |tee log.txt` and upload log.txt
