### ISSUE TITLE
Use in conjunction with other video_player implementation

### ISSUE THREAD

**Issue by Bonfra04** [wang-bin/fvp#170]
**Describe the bug**
I'd like to use FVP only for Linux builds.
For MacOS I'm fine with the default video_player implementation so i can just not include it in the `register_with` call.
For Windows, instead, I'm trying to experiment with the `video_player_win` package; this is sadly not possible since FVP implements all the interfaces at once, leading to the following error:
```
Plugin video_player:windows has conflicting direct dependency implementations:
  fvp
  video_player_win
To fix this issue, remove all but one of these dependencies from pubspec.yaml.

Please resolve the plugin implementation selection errors
```

**Expected behavior**
Some way to be more specific about which platform to include plugin-wise.

**Comment by wang-bin** [comment]
both fvp and video_player_win implement video_player, you must choose one, I can do nothing.

**Comment by Bonfra04** [comment]
Maybe is possible to split fvp into a main core and some "addons" like `fvp_windows`, `fvp_linux` and so on, and one includes only the needed ones? idk maybe its just too complicated and out of scope

**Comment by wang-bin** [comment]
> Maybe is possible to split fvp into a main core and some "addons" like `fvp_windows`, `fvp_linux` and so on, and one includes only the needed ones? idk maybe its just too complicated and out of scope

then the project will not be maintainable, because about 95% code are the same, the only difference is rendering code. what if a plugin supports all platforms and share the same code? i think it's a flaw of flutter. you can fork the repo and modify pubspec.yml to keep only linux platform

**Comment by wang-bin** [comment]
try master branch

**Comment by Bonfra04** [comment]
Hi, it seems like just by adding fvp to my pubspec, even if i register it only to other platforms still activates on windows

```dart
registerWith(options: {'platforms': [ 'linux' ] })
```

```
flutter: AsyncSnapshot<dynamic>(ConnectionState.done, null, UnimplementedError: init() has not been implemented., #0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)
#1      _videoPlayerPlatform (package:video_player/video_player.dart:34:21)
video_player.dart:34
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:440:25)
```

Do i nee to specify something else in the pubspec? 
```yaml
dependencies:
  video_player_win: # should take care of video playback on windows
  fvp:
    git: https://github.com/wang-bin/fvp.git
```

**Comment by wang-bin** [comment]
What's your flutter version? is the error same as fvp 0.28.0?

> flutter: AsyncSnapshot<dynamic>(ConnectionState.done, null, UnimplementedError: init() has not been implemented., #0      VideoPlayerPlatform.init (package:video_player_platform_interface/video_player_platform_interface.dart:43:5)

no plugin is used, both video_player_win and fvp are not included. what about removing fvp in dependencies?

**Comment by Bonfra04** [comment]
> What's your flutter version? is the error same as fvp 0.28.0?
```
flutter --version
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (4 days ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2
```
No the error is different. Using the main version it fails the entire `pub get` phase. Using the master branch it successfully gets the packages but at runtime it is loaded anyway.

When i remove fvp from the dependencies video_player_win automatically kicks in and its used without any other code modification. Since the same project also compiles for linux it'd be perfect to leave it (fvp) there and expect it to just to be enabled for linux

**Comment by wang-bin** [comment]
what about removing `registerWith`?

**Comment by Bonfra04** [comment]
```
platforms = [ "linux" ]
Platform.operatingSystem = "windows"
!platforms.contains(Platform.operatingSystem) == true # so enters the if
```
`VideoPlayerPlatform.instance` is a `WindowsVideoPlayer` before the assignment, after it gets the value of `_prevImpl` which is a `_PlaceholderImplementation`

**Comment by wang-bin** [comment]
_prevImpl should be null. can you find out when _prevImpl is set to _PlaceholderImplementation and show me the call stack from debugger?

**Comment by wang-bin** [comment]
you can use stack_trace package, or throw sn exception instead of print, then you can see call stack.

what about removing `dartPluginClass` lines in pubspec.yml? currently i only remove `implements` line. all these lines was added to register fvp automatically by dart_tooling generated code.

**Comment by Bonfra04** [comment]
hm nop i'm just getting the trace below by throwing an exception there, maybe vscode needs some special configuration to debug dart code invoked by the plugin automagic thing. 
```
flutter: `fvp` threw an error: Exception: Test. The app may not function as expected until you remove this plugin from pubspec.yaml
```
By commenting out the line with `dartPluginClass` for windows it is not called twice and `_prevImpl` is null when I manually call `registerWith`. The application then works as expected by not registering it for the windows platform (since its not in the list)

**Comment by wang-bin** [comment]
another try: do not remove dartPluginClass lines, but change `if (_prevImpl != null)` to `if (_prevImpl != null && VideoPlayerPlatform.instance is MdkVideoPlayerPlatform)`, it should also work.

**Comment by Bonfra04** [comment]
This way the first round of `registerVideoPlayerPlatformsWith` invoked by the plugin thing still executes fine, the second round invoked manually by `registerWith` does not satisfy the if and does not override `VideoPlayerPlatform.instance` so it works fine if the platform is not specified in the list. Specifying the platform in the list instead makes the previous if fail and let the function continue normally.

Little sidenote: in android this dual invocation appears not to occur, idk why but on my invocation of `registerWith`, `_prevImpl` is still null.

Anyway this seems to be the intended behaviour. Awesome :)

**Comment by wang-bin** [comment]
> Little sidenote: in android this dual invocation appears not to occur, idk why but on my invocation of registerWith, _prevImpl is still null.

because official implementation is preferred, so I didn't add dartPluginClass for android and not auto `registerWith`
