### ISSUE TITLE
Add HLS Support Inquiry

### ISSUE THREAD

**Issue by mohammadinfo** [wang-bin/fvp#178]
Hello, I wanted to know if your package supports HLS or not. If it doesn’t, do you have any plans to add this feature to your package?

**Comment by wang-bin** [comment]
hls is supported

**Comment by mohammadinfo** [comment]
How can I use it? Should I add any parameters to the video URL?

**Comment by wang-bin** [comment]
VideoPlayerController.networkUrl

**Comment by mohammadinfo** [comment]
![image](https://github.com/user-attachments/assets/dff22be0-a2e0-442a-bb5c-13850a8badd8)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(media open error, invalid or unsupported media, null, null)

**Comment by wang-bin** [comment]
show me the log
