### ISSUE TITLE
[android] 安卓下使用总是编译不过是什么问题

### ISSUE THREAD

**Issue by jiaguoxinzhi** [wang-bin/fvp#182]
错误信息：

`flutterSdkVersion: 3.24.0, 32400
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[0x7FFB72EF1440] ANOMALY: meaningless REX prefix used

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_player_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':video_player_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\android\sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process D:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\Administrator\.gradle\caches\transforms-4\486792b360ad15a7e12ab380a3e54ece-8659050b-be1c-4f93-acc5-6d6c4da3b0f5\transformed\output\temp\jmod --add-modules java.base --output C:\Users\Administrator\.gradle\caches\transforms-4\486792b360ad15a7e12ab380a3e54ece-8659050b-be1c-4f93-acc5-6d6c4da3b0f5\transformed\output\jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 24s
[0x7FFB72EF1440] ANOMALY: meaningless REX prefix used
Running Gradle task 'assembleDebug'...                             25.5s
Error: Gradle task assembleDebug failed with exit code 1`

跑的是示例的代码

https://github.com/wang-bin/mdk-examples/blob/master/flutter/simple/lib/multi_textures.dart

**Comment by wang-bin** [comment]
不清楚，你给的信息是依赖的模块编译错误。完整的编译日志可以发一下。github actions编译没问题

**Comment by jiaguoxinzhi** [comment]
我换到美国云主机上测试，的确很容易就编译过，
本地还没成功，我先再测试测试

**Comment by wang-bin** [comment]
用vpn呢
