### ISSUE TITLE
App won't launch after adding FVP to pubspec

### ISSUE THREAD

**Issue by realroywalker** [wang-bin/fvp#183]
**Describe the bug**
I have been trying to add FVP to my application, but found that it was not launching correctly after updating the code to include FVP.
When I run the app from vscode it builds but nothing actually launches (and no errors are given) - If I hit the pause button the debugger and then hit resume again the app loads up fine and works ok.

In an attempt to find the problem I created a brand new application and simply added the fvp line to the pubspec (it's using 0.28.0 currently) - as soon as only that line has been added I get the behaviour that is described above.. even without any additional FVP code or anything else added to the default sample app that gets generated when you run 'flutter create <name>'

**Expected behavior**
Application should launch correctly when FVP is present in the pubspec

**Log**
No logs as there are no errors generated.. steps to reproduce;
flutter create fvp_test
_run app (Windows 11 target)_ - Works OK
add 'fvp: ^0.28.0' into the dependencies section of pubspec
_run app (Windows 11 target)_ - UI never appears after building complete
click pause, then resume in the debugger toolbar - UI now opens and the app works ok

**Comment by realroywalker** [comment]
Thanks - I tried the Windows example from your link and it runs ok on the same PC that I'm developing my app on. 
The most simple code I have is here https://drive.google.com/file/d/1R7jWNBQMEtFJBjI6jQmz-JTc_cjrUkHN/view?usp=sharing
For me, that compiles ok but never becomes visible - unless I remove the fvp line from the pubspec and then it launches ok.

**Comment by realroywalker** [comment]
> It looks like this issue I reported a few months ago: #125 The app is only displayed after an hot reload

Thanks for the link, it certainly seems very similar but for me hot reload doesn't help - tried a few times and it never appears.
Using 'flutter run -d windows' from a command line does work though, so certainly seems like some kind of race condition with fvp and the debugger.

**Comment by xweiba** [comment]
> It looks like this issue I reported a few months ago: #125看起来就像我几个月前报告的这个问题： #125 The app is only displayed after an hot reload只有在热重载后才会显示应用程序

me too

**Comment by wang-bin** [comment]
what about removing `dartPluginClass:` lines in fvp's pubspec.yaml?

**Comment by wang-bin** [comment]
try master branch

**Comment by realroywalker** [comment]
Thanks - confirm this fixes the issue for me!
