### ISSUE TITLE
NDK is not configured for project

### ISSUE THREAD

**Issue by georrge1994** [wang-bin/fvp#187]
Added lib to the project and it stops to work. I got a compilation error:

Failed to query the value of property 'buildFlowServiceProperty\'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@7b9868a3 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':fvp'.
      > com.android.builder.errors.EvalIssueException: [CXX1101] NDK at C:\Users\darkt\AppData\Local\Android\Sdk\ndk-bundle did not have a source.properties file

Seems NDK is not configured for project.

**Comment by wang-bin** [comment]
A default version should be used. Is `C:\Users\darkt\AppData\Local\Android\Sdk\ndk-bundle` your ndk dir? what files in it?
