### ISSUE TITLE
[Bug | Android] Some audios are cut off

### ISSUE THREAD

**Issue by CaptainDario** [wang-bin/fvp#193]
**Describe the bug**

This bug is hard to describe, but basically, some '.wav' files are cut off when playing them on Android devices. See this video

https://github.com/user-attachments/assets/e5e914a3-11de-472f-ad34-42bd7c169e8b

**Expected behavior**

The same playback as on other devices.

**Code**

```dart
kanaSoundPlayer.setAsset("fe.wav");
kanaSoundPlayer.state = mdk.PlaybackState.playing;
```

[fe.wav.zip](https://github.com/user-attachments/files/18127085/fe.wav.zip)

**Comment by wang-bin** [comment]
what about `kanaSoundPlayer.audioBackends = ["AudioTrack"]`?

**Comment by CaptainDario** [comment]
This seems to fix it, thanks!
