### ISSUE TITLE
Does VideoPlayerController provide an API to retrieve the list of built-in subtitles in a video?

### ISSUE THREAD

**Issue by xweiba** [wang-bin/fvp#195]
I've just reviewed the source code but couldn't find any relevant information. Could you kindly guide me on how to proceed? I greatly appreciate your assistance!

**Comment by wang-bin** [comment]
controller.getMediaInfo()?.subtitle

**Comment by xweiba** [comment]
> getMediaInfo

![image](https://github.com/user-attachments/assets/d81c91a2-4cd4-47b7-a9a9-fb6c8f93bd86)
![image](https://github.com/user-attachments/assets/e16966a4-e92e-49ad-9ff0-6c96d594db0d)
![image](https://github.com/user-attachments/assets/b1b92ac3-b62a-4975-829f-6150deefb40c)

Has this API been moved? I see that the player instance should be able to retrieve mediaInfo, but I couldn't find the API interface to obtain the player instance through the controller.

**Comment by wang-bin** [comment]
in master branch, not 0.28.0

**Comment by xweiba** [comment]
> in master branch, not 0.28.0

Alright, I see it now. Thanks
