### ISSUE TITLE
commerical use?

### ISSUE THREAD

**Issue by zezo357** [wang-bin/fvp#26]
this is in https://github.com/wang-bin/mdk-sdk

```
License
Use for free: make sure your sdk is updated, otherwise you may see an QR image in the last frame. sdk will be released every month.
Free for opensource projects, QtAV donors and contributors, non-commercial softwares: you can acquire a key from me.
Commercial license: a key for an app for a single platform or multiple platforms.
```

is Commercial license not free on this package?

**Comment by wang-bin** [comment]
Yes. You can update libmdk to the latest version. In fact only opengl renderer will show qr, i.e. on android and linux.

**Comment by wang-bin** [comment]
the 2nd line says it's free for opensource softwares

**Comment by zezo357** [comment]
Okay I get it now, thank you

**Comment by wang-bin** [comment]
the latest version is free for all flutter users including commercial use

**Comment by zezo357** [comment]
> the latest version is free for all flutter users including commercial use

i am glad to hear that, 

but i marked my package as discontinued since i cant manage it anymore and its was taking alot of my time and i am working full time, meanwhile media_kit had the same controls i have in a better way so i moved to it

some of the video_player packages has good controls but none has the desktop feel since video_player doesnt support desktop by default 

i wish the best for you, since i really loved the performance of mdk, thank you for the awesome package and if you need my help at anytime i would be happy to help in any way i can
