### ISSUE TITLE
特殊伪造过的m3u8应该如何配置

### ISSUE THREAD

**Issue by Kumhy** [wang-bin/fvp#28]
类似：http://42.157.128.38:6969/jianghu/vipqq/489cb60e7c251ce490ffdd1a6f0d37fa.m3u8
里面的片段开头都是一张1x1的png，后面才是正常的视频
我看他们hls.js可以播放

mpv 播放会报错
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
 (+) Video --vid=1 (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.

fvp的输出：
failed to open va.dll
dev_->CreateTexture2D(&desc, nullptr, &tex)  ERROR@143fvp::FvpPlugin::HandleMethodCall: (80070057) ��������

**Comment by wang-bin** [comment]
那是他们私有格式了，能放才不正常
