### ISSUE TITLE
Do you intend to finish the implementation of this plugin?

### ISSUE THREAD

**Issue by insinfo** [wang-bin/fvp#3]
I've been using this video player on windows "video_player_windows" but the project is kind of stopped, although the video player works, it has some bugs. Do you intend to finish the implementation of this plugin?

https://github.com/anirudhb/flutter_packages
https://github.com/anirudhb/flutter_packages/tree/master/video_player_windows

**Comment by wang-bin** [comment]
I plan to implement a video_player plugin to support all platforms

**Comment by wang-bin** [comment]
now you can use standard video player with this plugin
