### ISSUE TITLE
m3u8 seeking/reseeking issue

### ISSUE THREAD

**Issue by hungryemon** [wang-bin/fvp#35]
.m3u8 videos once seeked, can't reseek until previous seekpoint video fully loads. the seekslider goes to previous point always.

**Comment by wang-bin** [comment]
try the last code. finally will go to the last seek position.

**Comment by hungryemon** [comment]
still a bit buggy in seekbar

**Comment by wang-bin** [comment]
not all seek requests will be dropped, for example an executing seek request. so the seek bar progress will go to a previous position. if it's not a network stream, the result pretty good. what behavior do you expect?

**Comment by wang-bin** [comment]
fixed in the latest version
