### ISSUE TITLE
can play rtsp/rtmp?

### ISSUE THREAD

**Issue by xiaodusx1** [wang-bin/fvp#36]
if can use FFmpeg to play rtsp/rtmp or user FFmpeg cli.can give a simple example?

**Comment by wang-bin** [comment]
Yes you can, `VideoPlayerController.network('rtsp://......');`. 

Default settings for rtsp is not low latency, i'm considering adding more settings. Currently you can enable low latency via

```
registerWith({options: {
  'player': {
      'avformat.analyzeduration': '10000',
      'avformat.probesize': '1000',
      'avformat.fpsprobesize': '0',
      'avformat.fflags': 'avformat.fflags',
      'avformat.avioflags': 'direct',
    }
  });
```

**Comment by xiaodusx1** [comment]
ok,It work,i just see:'VideoPlayerController.network' is deprecated and shouldn't be used. Use VideoPlayerController.networkUrl instead.and i Uri.parse("http://XX") it work,but Uri("rtsp://XX") ,use networkUrl I does't work.

**Comment by wang-bin** [comment]
`Uri("rtsp://XX")` is wrong, try `Uri.parse("rtsp://XX")`

**Comment by wang-bin** [comment]
sorry, rtsp and rtmp were disabled. the latest code should work.

**Comment by xiaodusx1** [comment]
> sorry, rtsp and rtmp were disabled. the latest code should work.

thank you for reply
