### ISSUE TITLE
Audio player texture

### ISSUE THREAD

**Issue by mohammadinfo** [wang-bin/fvp#37]
Hi !
The audio player texture is only visible when the current position of the music changes, otherwise only a black screen is played.

**Comment by wang-bin** [comment]
do you mean music with cover art?

**Comment by mohammadinfo** [comment]
Yeah

**Comment by wang-bin** [comment]
show me the log

**Comment by mohammadinfo** [comment]
When I change the position with the slider, everything is okay. However, by default, all I can see is a black screen with sound.

**Comment by wang-bin** [comment]
i need your log, or a minimal example to reproduce.

**Comment by mohammadinfo** [comment]
https://github.com/wang-bin/fvp/assets/62583428/00697904-e01c-482d-823a-80bc91144a36

**Comment by mohammadinfo** [comment]
If you need log tell me and I will send it.

**Comment by mohammadinfo** [comment]
and after I change position with slider I got this :

flutter: INFO: 2023-09-14 19:03:29.719223: 000002C348B0C100-MediaControl::seek(pos: 61838, flag:0X402 +FromStart). now: 10215
flutter: INFO: 2023-09-14 19:03:29.719223: default 000002C338A56E00-FrameReader::seek(61838, 0X402)
flutter: INFO: 2023-09-14 19:03:29.719223: default 000002C338A56E00 FrameReader::update MediaStatus 0X124=>0X1A4
flutter: FINE: 2023-09-14 19:03:29.719223: 784878272 player3037760933856 onMediaStatus: MediaStatus(+loaded+prepared+buffered) => MediaStatus(+loaded+prepared+buffered)
flutter: INFO: 2023-09-14 19:03:29.719223: 000002C338A56E00 default FrameReaderImpl::seekTo(61838, 0X402 #34)
flutter: INFO: 2023-09-14 19:03:29.720241: __int64 __cdecl mdk::abi::PacketIOWrapper::seek(__int64,enum mdk::abi::SeekFlag)@528 seek target(from 25): 61838ms, flags: +FromStart. now: 8.803265
flutter: INFO: 2023-09-14 19:03:29.720241: default 000002C338A56E00 FrameReader::update MediaStatus 0X1A4=>0X1A4
flutter: INFO: 2023-09-14 19:03:29.720241: Seek start. target time: 61863000 avseek flags: 1
flutter: INFO: 2023-09-14 19:03:29.720241: Seek end
flutter: INFO: 2023-09-14 19:03:29.720241: 1 packets is read after seek. read more to get target pts
flutter: INFO: 2023-09-14 19:03:29.722236: 1 packets is read after seek. seek result pts: 61.858s, requested: 61863
flutter: INFO: 2023-09-14 19:03:29.722236: default 000002C338A56E00 FrameReader::update MediaStatus 0X1A4=>0X124
flutter: FINE: 2023-09-14 19:03:29.722236: 784878272 player3037760933856 onMediaStatus: MediaStatus(+loaded+prepared+buffered) => MediaStatus(+loaded+prepared+buffered)
flutter: INFO: 2023-09-14 19:03:29.722236: seek_drop_non_video_: 0 ms, seek_wait_frame_: 1...
flutter: INFO: 2023-09-14 19:03:29.722236: starting decode loop thread mdk.vdec1@15132
flutter: FINE: 2023-09-14 19:03:29.722236: 784878272 player3037760933856 onEvent: thread.video 1
flutter: INFO: 2023-09-14 19:03:29.722236: video stream#1 starting decoding loop from decoder index 0...
flutter: INFO: 2023-09-14 19:03:29.722236: creating video decoder: MFT:d3d=11...
flutter: INFO: 2023-09-14 19:03:29.722236: opening video decoder: MFT...
flutter: INFO: 2023-09-14 19:03:29.722236: uninit com required for MFT: true
flutter: INFO: 2023-09-14 19:03:29.723237: 4MFT flags: 81
flutter: INFO: 2023-09-14 19:03:29.733409: 1 MFT class activates found
flutter: INFO: 2023-09-14 19:03:29.733409: IMFActivate[0] attributes:
flutter: INFO: 2023-09-14 19:03:29.733409: 6 attributes: MFT_FRIENDLY_NAME_Attribute=MJPEG Decoder MFT, MFT_INPUT_TYPES_Attributes=(32)[{MFMediaType_Video,'MJPG'}], MFT_TRANSFORM_CLSID_Attribute={cb17e772-e1cc-4633-8450-5617af577905}, MFT_OUTPUT_TYPES_Attributes=(64)[{MFMediaType_Video,MFVideoFormat_YUY2},{MFMediaType_Video,MFVideoFormat_NV12}], MF_TRANSFORM_FLAGS_Attribute=1, MF_TRANSFORM_CATEGORY_Attribute=MFT_CATEGORY_VIDEO_DECODER,
flutter: INFO: 2023-09-14 19:03:29.733409: Activating IMFActivate: MJPEG Decoder MFT
flutter: INFO: 2023-09-14 19:03:29.734410: a->GetUINT32(MF_SA_D3D11_AWARE, &d3d_aware)  ERROR@225mdk::abi::MFTVideoDecoder::onMFTCreated: (c00d36e6) The requested attribute was not found.
flutter: INFO: 2023-09-14 19:03:29.734410:
flutter: INFO: 2023-09-14 19:03:29.734410: Selected MFT attributes:
flutter: INFO: 2023-09-14 19:03:29.734410: 3 attributes: CODECAPI_AVDecNumWorkerThreads=20, CODECAPI_AVLowLatencyMode=1, CODECAPI_AVDecVideoAcceleration_H264=1,
flutter: INFO: 2023-09-14 19:03:29.734410: stream cout: in=1, out=1
flutter: INFO: 2023-09-14 19:03:29.734410: mdk::abi::MFTCodec::selectInputType
flutter: INFO: 2023-09-14 19:03:29.734410: 2 attributes: MF_MT_MAJOR_TYPE=MFMediaType_Video, MF_MT_SUBTYPE='MJPG',
flutter: INFO: 2023-09-14 19:03:29.734410: selected IMFMediaType index: 0
flutter: INFO: 2023-09-14 19:03:29.734410: SetInputType:
flutter: INFO: 2023-09-14 19:03:29.734410: 4 attributes: MF_MT_FRAME_SIZE=6120328398225 (1425x1425), MF_MT_MAJOR_TYPE=MFMediaType_Video, MF_MT_INTERLACE_MODE=7, MF_MT_SUBTYPE='MJPG',
flutter: INFO: 2023-09-14 19:03:29.734410: (hr = mft_->SetInputType(stream_id, type.Get(), flags))  ERROR@362mdk::abi::MFTCodec::selectInputType: (c00d36b4) The data specified for the media type is invalid, inconsistent, or not supported by this object.
flutter: INFO: 2023-09-14 19:03:29.734410:
flutter: WARNING: 2023-09-14 19:03:29.734410: ERROR! failed to setup decoder: video
flutter: FINE: 2023-09-14 19:03:29.734410: 784878272 player3037760933856 onEvent: decoder.video -1
flutter: INFO: 2023-09-14 19:03:29.734410: unsupported pixel format for dxgi
flutter: INFO: 2023-09-14 19:03:29.734410: 0-track seek end video frame @0.000000 seek_pos_: 61838
flutter: INFO: 2023-09-14 19:03:29.734410: try the next decoder if available
flutter: INFO: 2023-09-14 19:03:29.734410: video stream#1 starting decoding loop from decoder index 1...
flutter: INFO: 2023-09-14 19:03:29.734410: creating video decoder: D3D11...
flutter: INFO: 2023-09-14 19:03:29.734410: opening video decoder: D3D11...
flutter: INFO: 2023-09-14 19:03:29.734410: opening ffmpeg video decoder: mjpeg ...
flutter: INFO: 2023-09-14 19:03:29.734410: 000002C33EB5ED60->mdk::abi::D3D11NativeBufferPool::D3D11NativeBufferPool

flutter: INFO: 2023-09-14 19:03:29.738927: audio stream#0 is seeking... got flush pkt. flush decoder and  drop frames until seek target 61.8630s...
flutter: INFO: 2023-09-14 19:03:29.738927: invalid audio frame @-1.000000
flutter: INFO: 2023-09-14 19:03:29.738927: #34/34 audio seek_done: 1, seek_wait_frame_: 1/1
flutter: INFO: 2023-09-14 19:03:29.738927: audio stream#0 sending 1 invalid AOT frame @61.857959s. seeking: 0
flutter: INFO: 2023-09-14 19:03:29.738927: 000002C348B0C100 seek end audio frame @61.857959 seek_pos_: -1, sync_ao_ 1
flutter: INFO: 2023-09-14 19:03:29.753329: default FrameReader000002C338A56E00 #34 seekComplete 61857
flutter: INFO: 2023-09-14 19:03:29.753329: default 000002C338A56E00 FrameReader::update MediaStatus 0X124=>0X124
flutter: INFO: 2023-09-14 19:03:29.753329: default FrameReader 000002C338A56E00 callbacks 3, seeking: 0, seekComplete#34 @61857
flutter: INFO: 2023-09-14 19:03:29.761932: AVCodec.Video[mjpeg.] decoder: 1 Single threads
flutter: INFO: 2023-09-14 19:03:29.761932: unsupported avcodec options:  hwcontext=d3d11va
flutter: INFO: 2023-09-14 19:03:29.761932: mjpeg yuv420p, bpc:8, bpp:12(8,8,8), channels:(1,1,1), map: 0 1 2 0 1425x1425
flutter: FINE: 2023-09-14 19:03:29.761932: 784878272 player3037760933856 onEvent: decoder.video 0
flutter: INFO: 2023-09-14 19:03:29.761932: decode stored recovery packets: 1
flutter: INFO: 2023-09-14 19:03:29.761932: mjpeg codec pixel format list: (expected d3d11)
flutter: INFO: 2023-09-14 19:03:29.761932: cuda
flutter: INFO: 2023-09-14 19:03:29.761932: vaapi
flutter: INFO: 2023-09-14 19:03:29.761932: yuvj420p
flutter: INFO: 2023-09-14 19:03:29.761932: hwdec not available, sw fallback is disabled
flutter: FINE: 2023-09-14 19:03:29.761932: 784878272 player3037760933856 onEvent: decoder.video 0
flutter: INFO: 2023-09-14 19:03:29.761932: Error ret @113 D:\a\mdk-sdk\mdk-sdk\mdk\ffmpeg\plugin\AVCoderBase.cpp: (0xffffffea) Invalid argument
flutter: WARNING: 2023-09-14 19:03:29.761932: video stream#1 failed to decode recovery packets
flutter: INFO: 2023-09-14 19:03:29.769237: 000002C33EB5ED60->mdk::abi::D3D11NativeBufferPool::~D3D11NativeBufferPool

flutter: INFO: 2023-09-14 19:03:29.769237: 000002C33EB5EE48__cdecl UGL::opengl::Context::Local<struct mdk::abi::D3D11NativeBufferPool::ctx_res_t,struct mdk::abi::D3D11NativeBufferPool::ctx_res_t>::~Local(void)000000000000001E count: 0
flutter: INFO: 2023-09-14 19:03:29.769237: 000002C33EB5ED60__cdecl mdk::abi::NativeVideoBufferPool::~NativeVideoBufferPool(void)
flutter: INFO: 2023-09-14 19:03:29.769237: try the next decoder if available
flutter: INFO: 2023-09-14 19:03:29.769237: video stream#1 starting decoding loop from decoder index 2...
flutter: INFO: 2023-09-14 19:03:29.769237: creating video decoder: CUDA...
flutter: INFO: 2023-09-14 19:03:29.769237: opening video decoder: CUDA...
flutter: INFO: 2023-09-14 19:03:29.769237: CUDA device count: 1
flutter: INFO: 2023-09-14 19:03:29.769237: CUDA device 0(0/1): NVIDIA GeForce RTX 3050 Laptop GPU, compute 8.6 1740MHz
flutter: INFO: 2023-09-14 19:03:29.778423: >>>>>>>>1st audio frame (after seek) rendered: 1, ao: 61857, a: 61857, delta: 0 +0.026122
flutter: INFO: 2023-09-14 19:03:29.778423: audio stream#0 AOT frame is sent
flutter: INFO: 2023-09-14 19:03:29.807921: cuda stream: 000002C33C84DA50
flutter: FINE: 2023-09-14 19:03:29.822213: 784878272 player3037760933856 onEvent: decoder.video 0
flutter: INFO: 2023-09-14 19:03:29.822213: decode stored recovery packets: 1
flutter: INFO: 2023-09-14 19:03:29.822213: video sequence is changed. recreate cuvid decoder. 8bit 1425x1425=>8bit 1440x1440
flutter: INFO: 2023-09-14 19:03:29.846314: video stream#1 is seeking... got flush pkt. flush decoder and  drop frames until seek target 61.8630s...
flutter: INFO: 2023-09-14 19:03:29.846314: invalid video frame @-1.000000
flutter: INFO: 2023-09-14 19:03:29.849854: video stream#1 EOF/EOS decoded. end: 1
flutter: INFO: 2023-09-14 19:03:29.849854: #34/34 video seek_done: 1, seek_wait_frame_: -1/0
flutter: INFO: 2023-09-14 19:03:29.849854: VideoRenderer WxH=1425.000000x1425.000000 1425.000000x1425.000000, frame: 1425x1425
flutter: INFO: 2023-09-14 19:03:29.849854: update transform 2d. scale: (1.000000, 1.000000), orientation: 0
flutter: INFO: 2023-09-14 19:03:29.849854: m: mat<4, 4>(
flutter: INFO: 2023-09-14 19:03:29.849854: 1  0  0  0
flutter: INFO: 2023-09-14 19:03:29.849854: 0  1  0  0
flutter: INFO: 2023-09-14 19:03:29.850857: 0  0  1  0
flutter: INFO: 2023-09-14 19:03:29.850857: 0  0  0  1
flutter: INFO: 2023-09-14 19:03:29.850857: )
flutter: INFO: 2023-09-14 19:03:29.850857: default FrameReader000002C338A56E00 #34 seekComplete 61857
flutter: INFO: 2023-09-14 19:03:29.850857: default 000002C338A56E00 FrameReader::update MediaStatus 0X124=>0X124
flutter: INFO: 2023-09-14 19:03:29.850857: default FrameReader 000002C338A56E00 callbacks 2, seeking: 0, seekComplete#34 @61857
flutter: INFO: 2023-09-14 19:03:29.850857: mdk::abi::CUDABufferPool::transfer_from_cuda404 cuMemcpy2DAsync(&cp, stream_) CUDA ERROR: 1 CUDA_ERROR_INVALID_VALUE; invalid argument
flutter: INFO: 2023-09-14 19:03:29.873358:
flutter: INFO: 2023-09-14 19:03:29.873358: CUDA interop with pinned host memory 0000000308000000
flutter: INFO: 2023-09-14 19:03:29.873358: unknown, bpc:0, bpp:0(), channels:(), map: 0 0 0 0 => host mapped nv12, bpc:8, bpp:12(8,16), channels:(1,2), map: 0 1 2 0
flutter: INFO: 2023-09-14 19:03:29.873358: channel map: mat<4, 4>(
flutter: INFO: 2023-09-14 19:03:29.873358: 1  0  0  0
flutter: INFO: 2023-09-14 19:03:29.873358: 0  1  0  0
flutter: INFO: 2023-09-14 19:03:29.873358: 0  0  1  0
flutter: INFO: 2023-09-14 19:03:29.873358: 0  0  0  1
flutter: INFO: 2023-09-14 19:03:29.873358: )
flutter: INFO: 2023-09-14 19:03:29.873358: frame format: nv12, bpc:8, bpp:12(8,16), channels:(1,2), map: 0 1 2 0
flutter: INFO: 2023-09-14 19:03:29.873358: dxgi format 0: DXGI_FORMAT_R8_UNORM
flutter: INFO: 2023-09-14 19:03:29.873358: dxgi format 1: DXGI_FORMAT_R8G8_UNORM
flutter: INFO: 2023-09-14 19:03:29.873358: frame color: unknown unknown gbr full. gamma: 2.200000, signal peak: 1.000000
flutter: INFO: 2023-09-14 19:03:29.873358:  -
flutter: INFO: 2023-09-14 19:03:29.873358: output color: bt709 unknown unknown full. gamma: 2.200000, signal peak: 1.000000
flutter: INFO: 2023-09-14 19:03:29.873358: rgb primaries matrix: mat<3, 3>(
flutter: INFO: 2023-09-14 19:03:29.873358: 1  -9.31323e-08  -2.98023e-08
flutter: INFO: 2023-09-14 19:03:29.873358: 1.74623e-09  1  3.72529e-09
flutter: INFO: 2023-09-14 19:03:29.873358: 3.72529e-09  1.49012e-08  1
flutter: INFO: 2023-09-14 19:03:29.873358: )
flutter: INFO: 2023-09-14 19:03:29.874365: color transform: mat<4, 4>(
flutter: INFO: 2023-09-14 19:03:29.874365: 1  0  1.5748  -0.7874
flutter: INFO: 2023-09-14 19:03:29.874365: 1  -0.187324  -0.468124  0.327724
flutter: INFO: 2023-09-14 19:03:29.874365: 1  1.8556  0  -0.9278
flutter: INFO: 2023-09-14 19:03:29.874365: 0  0  0  1
flutter: INFO: 2023-09-14 19:03:29.874365: )
flutter: INFO: 2023-09-14 19:03:29.876373: EQ: mat<4, 4>(
flutter: INFO: 2023-09-14 19:03:29.876373: 1  0  0  0
flutter: INFO: 2023-09-14 19:03:29.876373: 0  1  0  0
flutter: INFO: 2023-09-14 19:03:29.876373: 0  0  1  0
flutter: INFO: 2023-09-14 19:03:29.876373: 0  0  0  1
flutter: INFO: 2023-09-14 19:03:29.876373: )
flutter: INFO: 2023-09-14 19:03:29.876373: video stream#1 check loop range for EOS. dec_state.seeking: 0. end: 1
flutter: INFO: 2023-09-14 19:03:29.876373: default FrameReader000002C338A56E00 video stream#1 range loop end
flutter: INFO: 2023-09-14 19:03:29.876373: EOS video frame of track 0
flutter: INFO: 2023-09-14 19:03:29.876373: video stream#1 decoding loop is finished
flutter: FINE: 2023-09-14 19:03:29.876373: 784878272 player3037760933856 onEvent: thread.video 0
flutter: INFO: 2023-09-14 19:03:30.206138: 000002C348B0C100 void __cdecl mdk::abi::MediaControlPush::setState(enum mdk::abi::State)@969 requested state 1=>2, current state 1. status: 0X124
flutter: INFO: 2023-09-14 19:03:30.206138: default FrameReader000002C338A56E00 request to pause 1, loaded: 4.
flutter: INFO: 2023-09-14 19:03:30.206138: default FrameReader000002C338A56E00 state: 1=>1=>2, 0
flutter: INFO: 2023-09-14 19:03:30.206138: default FrameReader000002C338A56E00 state requested: 2, current: 1
flutter: INFO: 2023-09-14 19:03:30.214697: default FrameReader000002C338A56E00 state: 1=>2=>2, 1
flutter: INFO: 2023-09-14 19:03:30.214697: default FrameReader000002C338A56E00 update state: 1=>2
flutter: FINE: 2023-09-14 19:03:30.214697: 784878272 player3037760933856 onPlaybackStateChanged: PlaybackState.playing => PlaybackState.paused

**Comment by wang-bin** [comment]
try the latest code

**Comment by mohammadinfo** [comment]
Thanks.
