### ISSUE TITLE
if remove the _ControlsOverlay and click many times quickly will has a error

### ISSUE THREAD

**Issue by xiaodusx1** [wang-bin/fvp#39]
I set as Example and   remove the _ControlsOverlay :
AspectRatio(aspectRatio: _controller.value.aspectRatio,
            child: Stack(
              alignment: Alignment.bottomCenter,
              children: <Widget>[
                VideoPlayer(_controller),
                   //_ControlsOverlay(controller: _controller),
                   //VideoProgressIndicator(_controller, allowScrubbing: true),
              ],
            ),
          ),

when click many times quickly will has a error on player 
will has a error:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:597:24)
#1      new MdkVideoPlayer.<anonymous closure> (package:fvp/src/video_player_mdk.dart:53:19)
#2      new Player.<anonymous closure> (package:fvp/src/player.dart:61:23)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#7      _StreamController._add (dart:async/stream_controller.dart:650:7)

**Comment by wang-bin** [comment]
try the latest code

**Comment by andrews-k** [comment]
fvp: ^0.37.3  android 
`_StreamController.add` still throws an error in `MdkVideoPlayer`.

<img width="2230" height="896" alt="Image" src="https://github.com/user-attachments/assets/e4cbd3b2-67d7-4cf8-b6c8-e04ce36c7d03" />
