### ISSUE TITLE
linux 支持

### ISSUE THREAD

**Issue by 1056824847** [wang-bin/fvp#4]
请问这个会添加linux支持吗，目前使用dart_vlc,播放视频会有点卡顿和掉帧

**Comment by wang-bin** [comment]
会，我最近会先把mac和win的video_player插件实现了再开始加linux

**Comment by wang-bin** [comment]
比较顺利，最新代码已经支持插件和linux了，不过linux销毁播放器后好像有内存泄漏，原因还不清楚

**Comment by wang-bin** [comment]
flutter还是挺恶心的，每个平台都要搞不同的代码，linux还和gtk深度捆绑

**Comment by 1056824847** [comment]
这边测试可以播放,十分感谢！！！

**Comment by wang-bin** [comment]
现在支持所有系统了，只有linux还有内存泄漏后面再查

**Comment by wang-bin** [comment]
发布到pub.dev了
