### ISSUE TITLE
linux x64 银河麒麟 编译失败

### ISSUE THREAD

**Issue by 1056824847** [wang-bin/fvp#49]
![image](https://github.com/wang-bin/fvp/assets/44287872/993bd60b-0585-4360-921c-5983184a6d37)
![image](https://github.com/wang-bin/fvp/assets/44287872/62c71804-356b-4eaf-99d1-1b657ae9c00d)
你好，这边在flutter run 的时候一直提示这个错误，是环境问题吗？

**Comment by wang-bin** [comment]
flutter的问题，估计新版本增加了一些warnings，但是linux上强行让我们使用屎一样的glib，宏展开必然一堆可能用不到的函数，然后我们得再手动关闭这些警告。
https://github.com/wang-bin/fvp/blob/master/linux/CMakeLists.txt#L49 这里加一行
```
target_compile_options(${PLUGIN_NAME} PRIVATE -Wno-unused-function)
```

**Comment by 1056824847** [comment]
target_compile_options(${PLUGIN_NAME} PRIVATE -Wno-unused-function)
flutter 3.16 添加这一行后可以编译成功，但是无法播放视频
目前已降低flutter 版本号为 3.10.3 ，并在cmake 添加这一行后成功运行
谢谢指导

**Comment by wang-bin** [comment]
3.16请试下fvp最新的版本

**Comment by 1056824847** [comment]
已测试可以播放，谢谢
