### ISSUE TITLE
Faulting application name: gemini.exe, version: 1.0.0.1 Faulting module name: flutter_windows.dll

### ISSUE THREAD

**Issue by hussi-emblem** [wang-bin/fvp#60]
I am using FVP https://pub.dev/packages/fvp for playing local videos on windows screen but it crashes randomly 

this is the stacktrace of crash : 
Level	Date and Time	Source	Event ID	Task Category
Error	04/01/2024 16:45:59	Application Error	1000	(100)	"Faulting application name: gemini.exe, version: 1.0.0.1, time stamp: 0x65967535
Faulting module name: flutter_windows.dll, version: 0.0.0.0, time stamp: 0x65820f0d
Exception code: 0xc0000409
Fault offset: 0x0000000000d53ab9
Faulting process id: 0x2880
Faulting application start time: 0x01da3f2d68463a9d
Faulting application path: C:\Program Files (x86)\My Program\gemini.exe
Faulting module path: C:\Program Files (x86)\My Program\flutter_windows.dll
Report Id: bf718aaf-5d1d-4152-879d-e6ceceb65490
Faulting package full name: 
Faulting package-relative application ID: "

This crash happens randomly 

Device specs  : Windows 10 pro 8gb ram and i7 processor
Dual screen (it has an extended screen ) 2 videos are being played at a time on main and extended screen

**Comment by wang-bin** [comment]
what about 1 video? i need the log, see issue template

**Comment by hussi-emblem** [comment]
@wang-bin This crash is happening on a Windows Dual screen not happening if app is run on a Laptop with visual code so the only log that we get is windows system crash report which is 

Error 04/01/2024 16:45:59 Application Error 1000 (100) "Faulting application name: gemini.exe, version: 1.0.0.1, time stamp: 0x65967535
Faulting module name: flutter_windows.dll, version: 0.0.0.0, time stamp: 0x65820f0d
Exception code: 0xc0000409
Fault offset: 0x0000000000d53ab9
Faulting process id: 0x2880
Faulting application start time: 0x01da3f2d68463a9d
Faulting application path: C:\Program Files (x86)\My Program\gemini.exe
Faulting module path: C:\Program Files (x86)\My Program\flutter_windows.dll
Report Id: bf718aaf-5d1d-4152-879d-e6ceceb65490
Faulting package full name:
Faulting package-relative application ID: "

For single video it also happened, But crash is so random that it doesn't has any sequence

**Comment by wang-bin** [comment]
from the error report the crash happens in flutter. what about other flutter apps?

**Comment by hussi-emblem** [comment]
Crash happens when I launch the app through teamviewer.

**Comment by wang-bin** [comment]
what about other flutter apps

**Comment by hussi-emblem** [comment]
If same app is lunched wihout video player with team viewer then not crashing

**Comment by wang-bin** [comment]
how can i reproduce the crash, launch fvp example from another computer via teamviewer?  can you write the log to a file in your app?
