### ISSUE TITLE
How to run example in macos

### ISSUE THREAD

**Issue by shineFoyMylove** [wang-bin/fvp#69]
**Describe the bug**
Failed to run example in macos when run `pod install`.
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/ios/Desktop/temp_code/fvp-master/example/macos/Pods/mdk/mdk-sdk/lib/mdk.xcframework)

**Other**
Example project can run successfully on iphone device.

**Log**
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing FlutterMacOS (1.0.0)
Installing fvp (0.0.1)
Installing mdk (0.24.0)
Installing video_player_avfoundation (0.0.1)
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/ios/Desktop/temp_code/fvp-master/example/macos/Pods/mdk/mdk-sdk/lib/mdk.xcframework)

```
Flutter version
```
Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (4 months ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0
```

**Someone can help me how to solve the problem and run successfully on macos**

**Comment by wang-bin** [comment]
`flutter run -d macos`, not `pod install`. to run you own examples, see flutter run -d macos, not pod install.

**Comment by shineFoyMylove** [comment]
resolve it when update gem, ruby and reinstall cocoapods, Too bad i don't know why.
