### ISSUE TITLE
A small unimportant wish

### ISSUE THREAD

**Issue by DovgopolsSerj** [wang-bin/fvp#70]
The first is a wonderful package.
I don't use it as a video player, but as a SHOUTcast player.
It would be great to add the ability to get ICY metadata.
FFMpeg provides such an opportunity through the parameters icy, icy_metadata_headers, icy_metadata_packet.
Now we have to add a separate isolate that periodically makes a request and extracts this data.

**Comment by DovgopolsSerj** [comment]
This is not a protocol. This is the format of icecast streams.
Example:
When accessing this address, you need to specify the header
Icy-MetaData: 1
Then the response will contain the header:
icy-metaint
This is the length of the audio data followed by one byte containing the length of the metadata. If it is not equal to zero, the following length * 16 is read. This is a string that usually contains the artist-title representation.
Then the audio data is read again, etc.
Inside your package, this is taken into account somewhere. Otherwise, there would be stuttering on such streams in the places where the metadata goes.
icy_metadata_headers - these are the response headers that contain the name of the station, the address of the playlist, etc.

**Comment by DovgopolsSerj** [comment]
Sorry, example of stream:
https://radiorecord.hostingradio.ru/ibiza96.aacp

**Comment by wang-bin** [comment]
I know how to get icy metadata, and will add new MediaEvent and update MediaInfo. But if with video_player api, there is no way to notify user about metadata update.

**Comment by wang-bin** [comment]
the latest [build](https://sourceforge.net/projects/mdk-sdk/files/nightly/) add a new MediaEvent for icy metadata, you can download and replace manually, or run `flutter clean` to cleanup cached dependencies. `video_player` can't access the metadata, you have to use backend api in `mdk.dart`:
```dart
  player.onEvent((ev) {
      _log.fine(
          '$hashCode player$nativeHandle onEvent: ${ev.category} - ${ev.detail} - ${ev.error}');
      if (ev.category == 'metadata') {
        mediaInfo.metadata.forEach((key, value) {
          _log.fine('metadata: $key: $value');
        });
      }
    });
```

and the log will be
```
flutter: fvp.FINE: 13:40:41.100: 372425887 player5469513328 onEvent: metadata - icy - 0
flutter: fvp.FINE: 13:40:41.110: metadata: icy-name: ibiza
flutter: fvp.FINE: 13:40:41.110: metadata: icy-genre: various
flutter: fvp.FINE: 13:40:41.110: metadata: icy-br: 96
flutter: fvp.FINE: 13:40:41.110: metadata: icy-description: Stream transcoder based on liquidsoap
flutter: fvp.FINE: 13:40:41.110: metadata: StreamTitle: HAL STUCKER/JARDIN - Empire!
flutter: fvp.FINE: 13:40:41.110: metadata: icy-pub: 1
```
