### ISSUE TITLE
Improving the Metadata change event

### ISSUE THREAD

**Issue by DovgopolsSerj** [wang-bin/fvp#74]
Please make all changes to the event with the Metadata category.
If you now submit an mp3 file to the Player, the event does not occur. But already from the reader.buffering event, player.mediaInfo.metadata already contains all the tags of the file (artist, album, etc.).
This is very cool, despite the fact that no other actions are needed to show the cover. Mp3 file covers are immediately displayed on the texture.

**Comment by wang-bin** [comment]
added in the latest mdk-sdk
