### ISSUE TITLE
linux 构建生成cmake_install.cmake中的CMAKE_INSTALL_PREFIX不正确

### ISSUE THREAD

**Issue by Generalize** [wang-bin/fvp#77]
正常的cmake_install.cmake应该是：
```cmake
# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/yarun/usr/project/flutter_videos/build/linux/x64/release/bundle")
endif()
``` 
fvp构建却生成了：
```cmake
# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
``` 
fvp生成的install目录变成了/usr/local目录

**Comment by wang-bin** [comment]
[github actions](https://[productionresultssa6.blob.core.windows.net/actions-results/21a0ac6b-cb90-41c3-a1ac-d547d5468503/workflow-job-run-0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-20T02%3A54%3A06Z&sig=qAvJFo3KYMwFEXRS3nqdbkU8BeHKbg4HlPfFE%2BJu4Ec%3D&sp=r&spr=https&sr=b&st=2024-03-20T02%3A44%3A01Z&sv=2021-12-02](https://productionresultssa6.blob.core.windows.net/actions-results/21a0ac6b-cb90-41c3-a1ac-d547d5468503/workflow-job-run-0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-20T02%3A54%3A06Z&sig=qAvJFo3KYMwFEXRS3nqdbkU8BeHKbg4HlPfFE%2BJu4Ec%3D&sp=r&spr=https&sr=b&st=2024-03-20T02%3A44%3A01Z&sv=2021-12-02)) 编译日志里编译example会install，目录是正确的

**Comment by wang-bin** [comment]
无法复现
