### ISSUE TITLE
[Question] Is it possible to use the ffmpeg libs like the command line version?

### ISSUE THREAD

**Issue by CaptainDario** [wang-bin/fvp#80]
I just stumbled upon this package and am curious if one can reuse the ffmpeg libraries for other things. Therefore, I would like to ask if it is possible to use the dynamic library from this package like the command-line version from FFmpeg, for example, can a command like this `ffmpeg -i input.avi output.mp4` be executed.

**Comment by wang-bin** [comment]
this libffmpeg.so is the merged version of standard ffmpeg libraries(libavcodec + libavformat + libavutils + libavfilter + libswscale + libswresample), no command line code. ffmpeg command line tool source code is in https://github.com/FFmpeg/FFmpeg/tree/master/fftools, you have to slightly modify the code to build the tool as a dynamic/static library(maybe already exist on github), for example libffmpegcmd.so, and link against libffmpeg.so from this package.

**Comment by wang-bin** [comment]
this libffmpeg.so is build with https://github.com/wang-bin/avbuild
