### ISSUE TITLE
App crash on IOS and iPad 17 ,

### ISSUE THREAD

**Issue by someshswami9** [wang-bin/fvp#82]
**Describe the bug**
My flutter app crashed due to fvp ,
for registerwith used in main(),

fvp ^0.16.0

crashed 3 to 4 times for different different scenarios but in report got same error . 

first crashed when open the app. 
second when closed from background app,
and once when I am watching the video and changed the screen 

**Expected behavior**
App should not be crashed 

**Log**

Full log
will be attached to attachment
[testflight_feedback-9.zip](https://github.com/wang-bin/fvp/files/15126699/testflight_feedback-9.zip)

```
[testflight_feedback-9.zip](https://github.com/wang-bin/fvp/files/15126790/testflight_feedback-9.zip)

```
add the following lines before `registerWith()`
```
  Logger.root.level = Level.ALL;
  final df = DateFormat("HH:mm:ss.SSS");
  Logger.root.onRecord.listen((record) {
    print('${record.loggerName}.${record.level.name}: ${df.format(record.time)}: ${record.message}');
  });
import 'package:fvp/fvp.dart' as fvp;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  fvp.registerWith();
```
and
```
9   fvp                           	0x00000001058a96e0 std::__1::__throw_bad_function_call[abi:v160006]() + 52 (function.h:72)
10  fvp                           	0x00000001058aab84 std::__1::__function::__value_func<bool (mdk::MediaStatus, mdk::MediaStatus)>::operator()[abi:v160006](mdk::MediaStatus&&, mdk::MediaStatus&&) const + 4 (function.h:509)



```

**Comment by wang-bin** [comment]
the crash is fixed recently. please upgrade fvp, and run

```
flutter clean 
pod cache clean mdk 
find . -name Podfile.lock -delete
```

and build again

**Comment by someshswami9** [comment]
Still crashed on v0.17.0

**Comment by wang-bin** [comment]
show me crash log

**Comment by someshswami9** [comment]
Sorry for late reply. but same as above.

**Comment by wang-bin** [comment]
i need the log. if same crash log, then you dependecy is not upgraded.

**Comment by wang-bin** [comment]
try master branch
