### ISSUE TITLE
web compilation

### ISSUE THREAD

**Issue by zezo357** [wang-bin/fvp#9]
using with video_player will make the code not compile on web

can the registerWith be wrapped in conditional import ?
like this?
https://github.com/AR-CADE/petit_player/blob/main/lib/fvp_pollyfill.dart

**Comment by wang-bin** [comment]
I can add an option for `registerWith` to select platforms to enable

**Comment by wang-bin** [comment]
what you can do now is
```dart
if (!dart.library.html)
    registerWith();
````

**Comment by zezo357** [comment]
thank you
